mod compiler_block_tests;
mod compiler_class_tests;
mod compiler_closure_tests;
mod compiler_control_flow_tests;
mod compiler_core_tests;
mod compiler_expression_tests;
mod compiler_function_tests;
mod compiler_optimization_tests;
mod compiler_statement_tests;
