# Ripper reads a separator after a condition, a command given as the one
# argument in parentheses, calls on a command's `do` block, and `return` in
# a singleton class the way MRI's parser does. A form MRI rejects gives nil.
require "ripper"

SOURCES = [
  "if a\n;b\nend",
  "if a;;b end",
  "if a ;\n ; b end",
  "if a\n\nb\nend",
  "if a;\nb\nend",
  "if a\nthen b end",
  "if a; then b end",
  "while a\n;b\nend",
  "while a;;b end",
  "until a\n\nb\nend",
  "for x in a\n;b\nend",
  "for x in a;b;end",
  "unless a\n;b\nend",
  "if a\nelsif c\n;b\nend",
  "case a\nwhen 1\n;b\nend",
  "case a\nwhen 1; ;b\nend",
  "begin\n;a\nrescue\n;b\nend",
  "while a do ;b end",
  "p(a.b 1)",
  "p(bar [2])",
  "p(gather ())",
  "p(a.b 1, 2)",
  "p(foo 1)",
  "p(foo 1, 2)",
  "foo(1, bar 2)",
  "p(foo 1 do end)",
  "foo do\nend.bar do\nend",
  "foo do end.bar 1 do end",
  "class << self; return 1; end",
  "class A; class << self; return 1; end; end",
  "foo(a.b 1)",
  "p(foo a: 1)",
  "p(foo 1, bar do end)",
  "p((foo 1 do end))",
  "p(foo bar { baz 1 do end })",
  "foo 1 do end",
  "foo 1 do end.bar do end",
  "foo 1 do end.bar",
  "foo 1 do end.bar 2",
  "foo 1 do end.bar { }",
  "foo 1 do end.bar(2) do end",
  "def m; class << self; return 1; end; end",
  "def m; class A; return 1; end; end",
  "def m; foo { class << self; return 1; end }; end",
  "TracePoint.new :call do |tp|\nend.enable do\nend",
  "a.b 1 do end.c do end.d",
  "foo 1 do end.bar(2)",
  "foo 1 do end.bar.baz",
].freeze

SOURCES.each { |source| p Ripper.sexp(source) }
