// Written by scripts/generate_core_method_names.rb from Ruby 4.0.6.

/// The instance methods a core class or module defines in Ruby, by
/// visibility, which the method listings of a built-in value draw from.
pub(crate) struct CoreMethods {
    pub(crate) owner: &'static str,
    pub(crate) public: &'static [&'static str],
    pub(crate) private: &'static [&'static str],
    pub(crate) protected: &'static [&'static str],
}

pub(crate) const CORE_METHODS: &[CoreMethods] = &[
    CoreMethods {
        owner: "main",
        public: &["inspect", "to_s"],
        private: &[
            "define_method",
            "include",
            "private",
            "public",
            "ruby2_keywords",
            "using",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "Array",
        public: &[
            "&",
            "*",
            "+",
            "-",
            "<<",
            "<=>",
            "==",
            "[]",
            "[]=",
            "all?",
            "any?",
            "append",
            "assoc",
            "at",
            "bsearch",
            "bsearch_index",
            "clear",
            "collect",
            "collect!",
            "combination",
            "compact",
            "compact!",
            "concat",
            "count",
            "cycle",
            "deconstruct",
            "delete",
            "delete_at",
            "delete_if",
            "detect",
            "difference",
            "dig",
            "drop",
            "drop_while",
            "each",
            "each_index",
            "empty?",
            "eql?",
            "fetch",
            "fetch_values",
            "fill",
            "filter",
            "filter!",
            "find",
            "find_index",
            "first",
            "flatten",
            "flatten!",
            "freeze",
            "hash",
            "include?",
            "index",
            "insert",
            "inspect",
            "intersect?",
            "intersection",
            "join",
            "keep_if",
            "last",
            "length",
            "map",
            "map!",
            "max",
            "min",
            "minmax",
            "none?",
            "one?",
            "pack",
            "permutation",
            "pop",
            "prepend",
            "product",
            "push",
            "rassoc",
            "reject",
            "reject!",
            "repeated_combination",
            "repeated_permutation",
            "replace",
            "reverse",
            "reverse!",
            "reverse_each",
            "rfind",
            "rindex",
            "rotate",
            "rotate!",
            "sample",
            "select",
            "select!",
            "shift",
            "shuffle",
            "shuffle!",
            "size",
            "slice",
            "slice!",
            "sort",
            "sort!",
            "sort_by!",
            "sum",
            "take",
            "take_while",
            "to_a",
            "to_ary",
            "to_h",
            "to_s",
            "transpose",
            "union",
            "uniq",
            "uniq!",
            "unshift",
            "values_at",
            "zip",
            "|",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "BasicObject",
        public: &[
            "!",
            "!=",
            "==",
            "__id__",
            "__send__",
            "equal?",
            "instance_eval",
            "instance_exec",
        ],
        private: &[
            "initialize",
            "method_missing",
            "singleton_method_added",
            "singleton_method_removed",
            "singleton_method_undefined",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "Binding",
        public: &[
            "clone",
            "dup",
            "eval",
            "implicit_parameter_defined?",
            "implicit_parameter_get",
            "implicit_parameters",
            "irb",
            "local_variable_defined?",
            "local_variable_get",
            "local_variable_set",
            "local_variables",
            "receiver",
            "source_location",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Class",
        public: &[
            "allocate",
            "attached_object",
            "new",
            "subclasses",
            "superclass",
        ],
        private: &["inherited", "initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Comparable",
        public: &["<", "<=", "==", ">", ">=", "between?", "clamp"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Complex",
        public: &[
            "*",
            "**",
            "+",
            "-",
            "-@",
            "/",
            "<=>",
            "==",
            "abs",
            "abs2",
            "angle",
            "arg",
            "coerce",
            "conj",
            "conjugate",
            "denominator",
            "eql?",
            "fdiv",
            "finite?",
            "hash",
            "imag",
            "imaginary",
            "infinite?",
            "inspect",
            "magnitude",
            "numerator",
            "phase",
            "polar",
            "quo",
            "rationalize",
            "real",
            "real?",
            "rect",
            "rectangular",
            "to_c",
            "to_f",
            "to_i",
            "to_r",
            "to_s",
        ],
        private: &["marshal_dump"],
        protected: &[],
    },
    CoreMethods {
        owner: "Data",
        public: &[
            "==",
            "deconstruct",
            "deconstruct_keys",
            "eql?",
            "hash",
            "inspect",
            "members",
            "to_h",
            "to_s",
            "with",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Dir",
        public: &[
            "chdir",
            "children",
            "close",
            "each",
            "each_child",
            "fileno",
            "inspect",
            "path",
            "pos",
            "pos=",
            "read",
            "rewind",
            "seek",
            "tell",
            "to_path",
        ],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Encoding",
        public: &[
            "_dump",
            "ascii_compatible?",
            "dummy?",
            "inspect",
            "name",
            "names",
            "to_s",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Encoding::Converter",
        public: &[
            "==",
            "convert",
            "convpath",
            "destination_encoding",
            "finish",
            "insert_output",
            "inspect",
            "last_error",
            "primitive_convert",
            "primitive_errinfo",
            "putback",
            "replacement",
            "replacement=",
            "source_encoding",
        ],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Encoding::InvalidByteSequenceError",
        public: &[
            "destination_encoding",
            "destination_encoding_name",
            "error_bytes",
            "incomplete_input?",
            "readagain_bytes",
            "source_encoding",
            "source_encoding_name",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Encoding::UndefinedConversionError",
        public: &[
            "destination_encoding",
            "destination_encoding_name",
            "error_char",
            "source_encoding",
            "source_encoding_name",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Enumerable",
        public: &[
            "all?",
            "any?",
            "chain",
            "chunk",
            "chunk_while",
            "collect",
            "collect_concat",
            "compact",
            "count",
            "cycle",
            "detect",
            "drop",
            "drop_while",
            "each_cons",
            "each_entry",
            "each_slice",
            "each_with_index",
            "each_with_object",
            "entries",
            "filter",
            "filter_map",
            "find",
            "find_all",
            "find_index",
            "first",
            "flat_map",
            "grep",
            "grep_v",
            "group_by",
            "include?",
            "inject",
            "lazy",
            "map",
            "max",
            "max_by",
            "member?",
            "min",
            "min_by",
            "minmax",
            "minmax_by",
            "none?",
            "one?",
            "partition",
            "reduce",
            "reject",
            "reverse_each",
            "select",
            "slice_after",
            "slice_before",
            "slice_when",
            "sort",
            "sort_by",
            "sum",
            "take",
            "take_while",
            "tally",
            "to_a",
            "to_h",
            "to_set",
            "uniq",
            "zip",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Enumerator",
        public: &[
            "+",
            "each",
            "each_with_index",
            "each_with_object",
            "feed",
            "inspect",
            "next",
            "next_values",
            "peek",
            "peek_values",
            "rewind",
            "size",
            "with_index",
            "with_object",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Enumerator::ArithmeticSequence",
        public: &[
            "==",
            "===",
            "begin",
            "each",
            "end",
            "eql?",
            "exclude_end?",
            "first",
            "hash",
            "inspect",
            "last",
            "size",
            "step",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Enumerator::Chain",
        public: &["each", "inspect", "rewind", "size"],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Enumerator::Generator",
        public: &["each"],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Enumerator::Lazy",
        public: &[
            "chunk",
            "chunk_while",
            "collect",
            "collect_concat",
            "compact",
            "drop",
            "drop_while",
            "eager",
            "enum_for",
            "filter",
            "filter_map",
            "find_all",
            "flat_map",
            "force",
            "grep",
            "grep_v",
            "lazy",
            "map",
            "reject",
            "select",
            "slice_after",
            "slice_before",
            "slice_when",
            "take",
            "take_while",
            "to_enum",
            "uniq",
            "with_index",
            "zip",
        ],
        private: &[
            "_enumerable_collect",
            "_enumerable_collect_concat",
            "_enumerable_drop",
            "_enumerable_drop_while",
            "_enumerable_filter",
            "_enumerable_filter_map",
            "_enumerable_find_all",
            "_enumerable_flat_map",
            "_enumerable_grep",
            "_enumerable_grep_v",
            "_enumerable_map",
            "_enumerable_reject",
            "_enumerable_select",
            "_enumerable_take",
            "_enumerable_take_while",
            "_enumerable_uniq",
            "_enumerable_with_index",
            "_enumerable_zip",
            "initialize",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "Enumerator::Producer",
        public: &["each"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Enumerator::Product",
        public: &["each", "inspect", "rewind", "size"],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Enumerator::Yielder",
        public: &["<<", "to_proc", "yield"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Exception",
        public: &[
            "==",
            "backtrace",
            "backtrace_locations",
            "cause",
            "detailed_message",
            "exception",
            "full_message",
            "inspect",
            "message",
            "respond_to?",
            "set_backtrace",
            "to_s",
        ],
        private: &["initialize", "method_missing", "respond_to_missing?"],
        protected: &[],
    },
    CoreMethods {
        owner: "FalseClass",
        public: &["&", "===", "^", "inspect", "to_s", "|"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Fiber",
        public: &[
            "alive?",
            "backtrace",
            "backtrace_locations",
            "blocking?",
            "inspect",
            "kill",
            "raise",
            "resume",
            "storage",
            "storage=",
            "to_s",
            "transfer",
        ],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "File",
        public: &[
            "atime",
            "birthtime",
            "chmod",
            "chown",
            "ctime",
            "flock",
            "lstat",
            "mtime",
            "size",
            "truncate",
        ],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "File::Stat",
        public: &[
            "<=>",
            "atime",
            "birthtime",
            "blksize",
            "blockdev?",
            "blocks",
            "chardev?",
            "ctime",
            "dev",
            "dev_major",
            "dev_minor",
            "directory?",
            "executable?",
            "executable_real?",
            "file?",
            "ftype",
            "gid",
            "grpowned?",
            "ino",
            "inspect",
            "mode",
            "mtime",
            "nlink",
            "owned?",
            "pipe?",
            "rdev",
            "rdev_major",
            "rdev_minor",
            "readable?",
            "readable_real?",
            "setgid?",
            "setuid?",
            "size",
            "size?",
            "socket?",
            "sticky?",
            "symlink?",
            "uid",
            "world_readable?",
            "world_writable?",
            "writable?",
            "writable_real?",
            "zero?",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "FileTest",
        public: &[],
        private: &[
            "blockdev?",
            "chardev?",
            "directory?",
            "empty?",
            "executable?",
            "executable_real?",
            "exist?",
            "file?",
            "grpowned?",
            "identical?",
            "owned?",
            "pipe?",
            "readable?",
            "readable_real?",
            "setgid?",
            "setuid?",
            "size",
            "size?",
            "socket?",
            "sticky?",
            "symlink?",
            "world_readable?",
            "world_writable?",
            "writable?",
            "writable_real?",
            "zero?",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "Float",
        public: &[
            "%",
            "*",
            "**",
            "+",
            "-",
            "-@",
            "/",
            "<",
            "<=",
            "<=>",
            "==",
            "===",
            ">",
            ">=",
            "abs",
            "angle",
            "arg",
            "ceil",
            "coerce",
            "denominator",
            "divmod",
            "eql?",
            "fdiv",
            "finite?",
            "floor",
            "hash",
            "infinite?",
            "inspect",
            "magnitude",
            "modulo",
            "nan?",
            "negative?",
            "next_float",
            "numerator",
            "phase",
            "positive?",
            "prev_float",
            "quo",
            "rationalize",
            "round",
            "to_f",
            "to_i",
            "to_int",
            "to_r",
            "to_s",
            "truncate",
            "zero?",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "FrozenError",
        public: &["receiver"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "GC",
        public: &["garbage_collect"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Hash",
        public: &[
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "[]",
            "[]=",
            "any?",
            "assoc",
            "clear",
            "compact",
            "compact!",
            "compare_by_identity",
            "compare_by_identity?",
            "deconstruct_keys",
            "default",
            "default=",
            "default_proc",
            "default_proc=",
            "delete",
            "delete_if",
            "dig",
            "each",
            "each_key",
            "each_pair",
            "each_value",
            "empty?",
            "eql?",
            "except",
            "fetch",
            "fetch_values",
            "filter",
            "filter!",
            "flatten",
            "freeze",
            "has_key?",
            "has_value?",
            "hash",
            "include?",
            "inspect",
            "invert",
            "keep_if",
            "key",
            "key?",
            "keys",
            "length",
            "member?",
            "merge",
            "merge!",
            "rassoc",
            "rehash",
            "reject",
            "reject!",
            "replace",
            "select",
            "select!",
            "shift",
            "size",
            "slice",
            "store",
            "to_a",
            "to_h",
            "to_hash",
            "to_proc",
            "to_s",
            "transform_keys",
            "transform_keys!",
            "transform_values",
            "transform_values!",
            "update",
            "value?",
            "values",
            "values_at",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "IO",
        public: &[
            "<<",
            "advise",
            "autoclose=",
            "autoclose?",
            "binmode",
            "binmode?",
            "close",
            "close_on_exec=",
            "close_on_exec?",
            "close_read",
            "close_write",
            "closed?",
            "each",
            "each_byte",
            "each_char",
            "each_codepoint",
            "each_line",
            "eof",
            "eof?",
            "external_encoding",
            "fcntl",
            "fdatasync",
            "fileno",
            "flush",
            "fsync",
            "getbyte",
            "getc",
            "gets",
            "inspect",
            "internal_encoding",
            "ioctl",
            "isatty",
            "lineno",
            "lineno=",
            "path",
            "pid",
            "pos",
            "pos=",
            "pread",
            "print",
            "printf",
            "putc",
            "puts",
            "pwrite",
            "read",
            "read_nonblock",
            "readbyte",
            "readchar",
            "readline",
            "readlines",
            "readpartial",
            "reopen",
            "rewind",
            "seek",
            "set_encoding",
            "set_encoding_by_bom",
            "stat",
            "sync",
            "sync=",
            "sysread",
            "sysseek",
            "syswrite",
            "tell",
            "timeout",
            "timeout=",
            "to_i",
            "to_io",
            "to_path",
            "tty?",
            "ungetbyte",
            "ungetc",
            "wait",
            "wait_priority",
            "wait_readable",
            "wait_writable",
            "write",
            "write_nonblock",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "IO::Buffer",
        public: &[
            "&",
            "<=>",
            "^",
            "and!",
            "clear",
            "copy",
            "each",
            "each_byte",
            "empty?",
            "external?",
            "free",
            "get_string",
            "get_value",
            "get_values",
            "hexdump",
            "inspect",
            "internal?",
            "locked",
            "locked?",
            "mapped?",
            "not!",
            "null?",
            "or!",
            "pread",
            "private?",
            "pwrite",
            "read",
            "readonly?",
            "resize",
            "set_string",
            "set_value",
            "set_values",
            "shared?",
            "size",
            "slice",
            "to_s",
            "transfer",
            "valid?",
            "values",
            "write",
            "xor!",
            "|",
            "~",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Integer",
        public: &[
            "%",
            "&",
            "*",
            "**",
            "+",
            "-",
            "-@",
            "/",
            "<",
            "<<",
            "<=",
            "<=>",
            "==",
            "===",
            ">",
            ">=",
            ">>",
            "[]",
            "^",
            "abs",
            "allbits?",
            "anybits?",
            "bit_length",
            "ceil",
            "ceildiv",
            "chr",
            "coerce",
            "denominator",
            "digits",
            "div",
            "divmod",
            "downto",
            "even?",
            "fdiv",
            "floor",
            "gcd",
            "gcdlcm",
            "inspect",
            "integer?",
            "lcm",
            "magnitude",
            "modulo",
            "next",
            "nobits?",
            "numerator",
            "odd?",
            "ord",
            "pow",
            "pred",
            "rationalize",
            "remainder",
            "round",
            "size",
            "succ",
            "times",
            "to_f",
            "to_i",
            "to_int",
            "to_r",
            "to_s",
            "truncate",
            "upto",
            "zero?",
            "|",
            "~",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Interrupt",
        public: &[],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Kernel",
        public: &[
            "!~",
            "<=>",
            "===",
            "class",
            "clone",
            "define_singleton_method",
            "display",
            "dup",
            "enum_for",
            "eql?",
            "extend",
            "freeze",
            "frozen?",
            "hash",
            "inspect",
            "instance_of?",
            "instance_variable_defined?",
            "instance_variable_get",
            "instance_variable_set",
            "instance_variables",
            "is_a?",
            "itself",
            "kind_of?",
            "method",
            "methods",
            "nil?",
            "object_id",
            "private_methods",
            "protected_methods",
            "public_method",
            "public_methods",
            "public_send",
            "remove_instance_variable",
            "respond_to?",
            "send",
            "singleton_class",
            "singleton_method",
            "singleton_methods",
            "tap",
            "then",
            "to_enum",
            "to_s",
            "yield_self",
        ],
        private: &[
            "Array",
            "Complex",
            "Float",
            "Hash",
            "Integer",
            "Pathname",
            "Rational",
            "String",
            "__callee__",
            "__dir__",
            "__method__",
            "`",
            "abort",
            "at_exit",
            "autoload",
            "autoload?",
            "binding",
            "block_given?",
            "caller",
            "caller_locations",
            "catch",
            "eval",
            "exec",
            "exit",
            "exit!",
            "fail",
            "fork",
            "format",
            "gets",
            "global_variables",
            "initialize_clone",
            "initialize_copy",
            "initialize_dup",
            "instance_variables_to_inspect",
            "iterator?",
            "lambda",
            "load",
            "local_variables",
            "loop",
            "open",
            "p",
            "pp",
            "print",
            "printf",
            "proc",
            "putc",
            "puts",
            "raise",
            "rand",
            "readline",
            "readlines",
            "require",
            "require_relative",
            "respond_to_missing?",
            "select",
            "set_trace_func",
            "sleep",
            "spawn",
            "sprintf",
            "srand",
            "syscall",
            "system",
            "test",
            "throw",
            "trace_var",
            "trap",
            "untrace_var",
            "warn",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "KeyError",
        public: &["key", "receiver"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "LoadError",
        public: &["path"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "LocalJumpError",
        public: &["exit_value", "reason"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Marshal",
        public: &[],
        private: &["dump"],
        protected: &[],
    },
    CoreMethods {
        owner: "MatchData",
        public: &[
            "==",
            "[]",
            "begin",
            "bytebegin",
            "byteend",
            "byteoffset",
            "captures",
            "deconstruct",
            "deconstruct_keys",
            "end",
            "eql?",
            "hash",
            "inspect",
            "length",
            "match",
            "match_length",
            "named_captures",
            "names",
            "offset",
            "post_match",
            "pre_match",
            "regexp",
            "size",
            "string",
            "to_a",
            "to_s",
            "values_at",
        ],
        private: &["initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Math",
        public: &[],
        private: &[
            "acos", "acosh", "asin", "asinh", "atan", "atan2", "atanh", "cbrt", "cos", "cosh",
            "erf", "erfc", "exp", "expm1", "frexp", "gamma", "hypot", "ldexp", "lgamma", "log",
            "log10", "log1p", "log2", "sin", "sinh", "sqrt", "tan", "tanh",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "Method",
        public: &[
            "<<",
            "==",
            "===",
            ">>",
            "[]",
            "arity",
            "box",
            "call",
            "clone",
            "curry",
            "dup",
            "eql?",
            "hash",
            "inspect",
            "name",
            "original_name",
            "owner",
            "parameters",
            "receiver",
            "source_location",
            "super_method",
            "to_proc",
            "to_s",
            "unbind",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Module",
        public: &[
            "<",
            "<=",
            "<=>",
            "==",
            "===",
            ">",
            ">=",
            "alias_method",
            "ancestors",
            "attr",
            "attr_accessor",
            "attr_reader",
            "attr_writer",
            "autoload",
            "autoload?",
            "class_eval",
            "class_exec",
            "class_variable_defined?",
            "class_variable_get",
            "class_variable_set",
            "class_variables",
            "const_defined?",
            "const_get",
            "const_missing",
            "const_set",
            "const_source_location",
            "constants",
            "define_method",
            "deprecate_constant",
            "freeze",
            "include",
            "include?",
            "included_modules",
            "inspect",
            "instance_method",
            "instance_methods",
            "method_defined?",
            "module_eval",
            "module_exec",
            "name",
            "prepend",
            "private_class_method",
            "private_constant",
            "private_instance_methods",
            "private_method_defined?",
            "protected_instance_methods",
            "protected_method_defined?",
            "public_class_method",
            "public_constant",
            "public_instance_method",
            "public_instance_methods",
            "public_method_defined?",
            "refinements",
            "remove_class_variable",
            "remove_method",
            "set_temporary_name",
            "singleton_class?",
            "to_s",
            "undef_method",
            "undefined_instance_methods",
        ],
        private: &[
            "append_features",
            "const_added",
            "extend_object",
            "extended",
            "included",
            "initialize",
            "initialize_clone",
            "method_added",
            "method_removed",
            "method_undefined",
            "module_function",
            "prepend_features",
            "prepended",
            "private",
            "protected",
            "public",
            "refine",
            "remove_const",
            "ruby2_keywords",
            "using",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "NameError",
        public: &["local_variables", "name", "receiver"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "NilClass",
        public: &[
            "&",
            "===",
            "=~",
            "^",
            "inspect",
            "nil?",
            "rationalize",
            "to_a",
            "to_c",
            "to_f",
            "to_h",
            "to_i",
            "to_r",
            "to_s",
            "|",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "NoMatchingPatternKeyError",
        public: &["key", "matchee"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "NoMethodError",
        public: &["args", "private_call?"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Numeric",
        public: &[
            "%",
            "+@",
            "-@",
            "<=>",
            "abs",
            "abs2",
            "angle",
            "arg",
            "ceil",
            "clone",
            "coerce",
            "conj",
            "conjugate",
            "denominator",
            "div",
            "divmod",
            "dup",
            "eql?",
            "fdiv",
            "finite?",
            "floor",
            "i",
            "imag",
            "imaginary",
            "infinite?",
            "integer?",
            "magnitude",
            "modulo",
            "negative?",
            "nonzero?",
            "numerator",
            "phase",
            "polar",
            "positive?",
            "quo",
            "real",
            "real?",
            "rect",
            "rectangular",
            "remainder",
            "round",
            "singleton_method_added",
            "step",
            "to_c",
            "to_int",
            "truncate",
            "zero?",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "ObjectSpace",
        public: &[],
        private: &[
            "_id2ref",
            "count_objects",
            "define_finalizer",
            "each_object",
            "garbage_collect",
            "undefine_finalizer",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "ObjectSpace::WeakKeyMap",
        public: &["[]", "[]=", "clear", "delete", "getkey", "inspect", "key?"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "ObjectSpace::WeakMap",
        public: &[
            "[]",
            "[]=",
            "delete",
            "each",
            "each_key",
            "each_pair",
            "each_value",
            "include?",
            "inspect",
            "key?",
            "keys",
            "length",
            "member?",
            "size",
            "values",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Proc",
        public: &[
            "<<",
            "==",
            "===",
            ">>",
            "[]",
            "arity",
            "binding",
            "call",
            "clone",
            "curry",
            "dup",
            "eql?",
            "hash",
            "inspect",
            "lambda?",
            "parameters",
            "ruby2_keywords",
            "source_location",
            "to_proc",
            "to_s",
            "yield",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Process",
        public: &[],
        private: &[
            "argv0",
            "clock_getres",
            "clock_gettime",
            "daemon",
            "detach",
            "egid",
            "egid=",
            "euid",
            "euid=",
            "getpgid",
            "getpgrp",
            "getpriority",
            "getrlimit",
            "getsid",
            "gid",
            "gid=",
            "groups",
            "groups=",
            "initgroups",
            "kill",
            "maxgroups",
            "maxgroups=",
            "pid",
            "ppid",
            "setpgid",
            "setpgrp",
            "setpriority",
            "setproctitle",
            "setrlimit",
            "setsid",
            "times",
            "uid",
            "uid=",
            "wait",
            "wait2",
            "waitall",
            "waitpid",
            "waitpid2",
            "warmup",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "Process::GID",
        public: &[],
        private: &[
            "change_privilege",
            "eid",
            "from_name",
            "grant_privilege",
            "re_exchange",
            "re_exchangeable?",
            "rid",
            "sid_available?",
            "switch",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "Process::Status",
        public: &[
            "==",
            "coredump?",
            "exited?",
            "exitstatus",
            "inspect",
            "pid",
            "signaled?",
            "stopped?",
            "stopsig",
            "success?",
            "termsig",
            "to_i",
            "to_s",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Process::Sys",
        public: &[],
        private: &[
            "getegid",
            "geteuid",
            "getgid",
            "getuid",
            "issetugid",
            "setegid",
            "seteuid",
            "setgid",
            "setregid",
            "setresgid",
            "setresuid",
            "setreuid",
            "setrgid",
            "setruid",
            "setuid",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "Process::Tms",
        public: &[
            "cstime", "cstime=", "cutime", "cutime=", "stime", "stime=", "utime", "utime=",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Process::UID",
        public: &[],
        private: &[
            "change_privilege",
            "eid",
            "from_name",
            "grant_privilege",
            "re_exchange",
            "re_exchangeable?",
            "rid",
            "sid_available?",
            "switch",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "Process::Waiter",
        public: &["pid"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Ractor",
        public: &[
            "<<",
            "[]",
            "[]=",
            "close",
            "default_port",
            "inspect",
            "join",
            "monitor",
            "name",
            "send",
            "to_s",
            "unmonitor",
            "value",
        ],
        private: &["receive", "recv"],
        protected: &[],
    },
    CoreMethods {
        owner: "Ractor::MovedObject",
        public: &[
            "!",
            "!=",
            "==",
            "__id__",
            "__send__",
            "equal?",
            "instance_eval",
            "instance_exec",
            "method_missing",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Ractor::Port",
        public: &["<<", "close", "closed?", "inspect", "receive", "send"],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Ractor::RemoteError",
        public: &["ractor"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Random",
        public: &["=="],
        private: &[
            "initialize_copy",
            "left",
            "marshal_dump",
            "marshal_load",
            "state",
        ],
        protected: &[],
    },
    CoreMethods {
        owner: "Random::Base",
        public: &["bytes", "rand", "seed"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Random::Formatter",
        public: &["rand", "random_number"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Range",
        public: &[
            "%",
            "==",
            "===",
            "begin",
            "bsearch",
            "count",
            "cover?",
            "each",
            "end",
            "entries",
            "eql?",
            "exclude_end?",
            "first",
            "hash",
            "include?",
            "inspect",
            "last",
            "max",
            "member?",
            "min",
            "minmax",
            "overlap?",
            "reverse_each",
            "size",
            "step",
            "to_a",
            "to_s",
            "to_set",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Rational",
        public: &[
            "*",
            "**",
            "+",
            "-",
            "-@",
            "/",
            "<=>",
            "==",
            "abs",
            "ceil",
            "coerce",
            "denominator",
            "fdiv",
            "floor",
            "hash",
            "inspect",
            "magnitude",
            "negative?",
            "numerator",
            "positive?",
            "quo",
            "rationalize",
            "round",
            "to_f",
            "to_i",
            "to_r",
            "to_s",
            "truncate",
        ],
        private: &["marshal_dump"],
        protected: &[],
    },
    CoreMethods {
        owner: "Refinement",
        public: &["target"],
        private: &["import_methods"],
        protected: &[],
    },
    CoreMethods {
        owner: "Regexp",
        public: &[
            "==",
            "===",
            "=~",
            "casefold?",
            "encoding",
            "eql?",
            "fixed_encoding?",
            "hash",
            "inspect",
            "match",
            "match?",
            "named_captures",
            "names",
            "options",
            "source",
            "timeout",
            "to_s",
            "~",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Ruby::Box",
        public: &[
            "eval",
            "inspect",
            "load",
            "load_path",
            "require",
            "require_relative",
        ],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Ruby::Box::Loader",
        public: &[],
        private: &["load", "require", "require_relative"],
        protected: &[],
    },
    CoreMethods {
        owner: "RubyVM::AbstractSyntaxTree::Location",
        public: &[
            "first_column",
            "first_lineno",
            "inspect",
            "last_column",
            "last_lineno",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "RubyVM::AbstractSyntaxTree::Node",
        public: &[
            "all_tokens",
            "children",
            "first_column",
            "first_lineno",
            "inspect",
            "last_column",
            "last_lineno",
            "locations",
            "node_id",
            "script_lines",
            "source",
            "tokens",
            "type",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "RubyVM::InstructionSequence",
        public: &[
            "absolute_path",
            "base_label",
            "disasm",
            "disassemble",
            "each_child",
            "eval",
            "first_lineno",
            "inspect",
            "label",
            "path",
            "script_lines",
            "to_a",
            "to_binary",
            "trace_points",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Set",
        public: &[
            "&",
            "+",
            "-",
            "<",
            "<<",
            "<=",
            "<=>",
            "==",
            "===",
            ">",
            ">=",
            "^",
            "add",
            "add?",
            "classify",
            "clear",
            "collect!",
            "compare_by_identity",
            "compare_by_identity?",
            "delete",
            "delete?",
            "delete_if",
            "difference",
            "disjoint?",
            "divide",
            "each",
            "empty?",
            "eql?",
            "filter!",
            "flatten",
            "flatten!",
            "hash",
            "include?",
            "inspect",
            "intersect?",
            "intersection",
            "join",
            "keep_if",
            "length",
            "map!",
            "member?",
            "merge",
            "proper_subset?",
            "proper_superset?",
            "reject!",
            "replace",
            "reset",
            "select!",
            "size",
            "subset?",
            "subtract",
            "superset?",
            "to_a",
            "to_s",
            "to_set",
            "union",
            "|",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Signal",
        public: &[],
        private: &["list", "signame", "trap"],
        protected: &[],
    },
    CoreMethods {
        owner: "SignalException",
        public: &["signm", "signo"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "StopIteration",
        public: &["result"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "String",
        public: &[
            "%",
            "*",
            "+",
            "+@",
            "-@",
            "<<",
            "<=>",
            "==",
            "===",
            "=~",
            "[]",
            "[]=",
            "append_as_bytes",
            "ascii_only?",
            "b",
            "byteindex",
            "byterindex",
            "bytes",
            "bytesize",
            "byteslice",
            "bytesplice",
            "capitalize",
            "capitalize!",
            "casecmp",
            "casecmp?",
            "center",
            "chars",
            "chomp",
            "chomp!",
            "chop",
            "chop!",
            "chr",
            "clear",
            "codepoints",
            "concat",
            "count",
            "crypt",
            "dedup",
            "delete",
            "delete!",
            "delete_prefix",
            "delete_prefix!",
            "delete_suffix",
            "delete_suffix!",
            "downcase",
            "downcase!",
            "dump",
            "dup",
            "each_byte",
            "each_char",
            "each_codepoint",
            "each_grapheme_cluster",
            "each_line",
            "empty?",
            "encode",
            "encode!",
            "encoding",
            "end_with?",
            "eql?",
            "force_encoding",
            "freeze",
            "getbyte",
            "grapheme_clusters",
            "gsub",
            "gsub!",
            "hash",
            "hex",
            "include?",
            "index",
            "insert",
            "inspect",
            "intern",
            "length",
            "lines",
            "ljust",
            "lstrip",
            "lstrip!",
            "match",
            "match?",
            "next",
            "next!",
            "oct",
            "ord",
            "partition",
            "prepend",
            "replace",
            "reverse",
            "reverse!",
            "rindex",
            "rjust",
            "rpartition",
            "rstrip",
            "rstrip!",
            "scan",
            "scrub",
            "scrub!",
            "setbyte",
            "size",
            "slice",
            "slice!",
            "split",
            "squeeze",
            "squeeze!",
            "start_with?",
            "strip",
            "strip!",
            "sub",
            "sub!",
            "succ",
            "succ!",
            "sum",
            "swapcase",
            "swapcase!",
            "to_c",
            "to_f",
            "to_i",
            "to_r",
            "to_s",
            "to_str",
            "to_sym",
            "tr",
            "tr!",
            "tr_s",
            "tr_s!",
            "undump",
            "unicode_normalize",
            "unicode_normalize!",
            "unicode_normalized?",
            "unpack",
            "unpack1",
            "upcase",
            "upcase!",
            "upto",
            "valid_encoding?",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Struct",
        public: &[
            "==",
            "[]",
            "[]=",
            "deconstruct",
            "deconstruct_keys",
            "dig",
            "each",
            "each_pair",
            "eql?",
            "filter",
            "hash",
            "inspect",
            "length",
            "members",
            "select",
            "size",
            "to_a",
            "to_h",
            "to_s",
            "values",
            "values_at",
        ],
        private: &["initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "Symbol",
        public: &[
            "<=>",
            "==",
            "===",
            "=~",
            "[]",
            "capitalize",
            "casecmp",
            "casecmp?",
            "downcase",
            "empty?",
            "encoding",
            "end_with?",
            "id2name",
            "inspect",
            "intern",
            "length",
            "match",
            "match?",
            "name",
            "next",
            "size",
            "slice",
            "start_with?",
            "succ",
            "swapcase",
            "to_proc",
            "to_s",
            "to_sym",
            "upcase",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "SyntaxError",
        public: &["path"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "SystemCallError",
        public: &["errno"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "SystemExit",
        public: &["status", "success?"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Thread",
        public: &[
            "[]",
            "[]=",
            "abort_on_exception",
            "abort_on_exception=",
            "add_trace_func",
            "alive?",
            "backtrace",
            "backtrace_locations",
            "exit",
            "fetch",
            "group",
            "inspect",
            "join",
            "key?",
            "keys",
            "kill",
            "name",
            "name=",
            "native_thread_id",
            "pending_interrupt?",
            "priority",
            "priority=",
            "raise",
            "report_on_exception",
            "report_on_exception=",
            "run",
            "set_trace_func",
            "status",
            "stop?",
            "terminate",
            "thread_variable?",
            "thread_variable_get",
            "thread_variable_set",
            "thread_variables",
            "to_s",
            "value",
            "wakeup",
        ],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Thread::Backtrace::Location",
        public: &[
            "absolute_path",
            "base_label",
            "inspect",
            "label",
            "lineno",
            "path",
            "to_s",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Thread::ConditionVariable",
        public: &["broadcast", "marshal_dump", "signal", "wait"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Thread::Mutex",
        public: &[
            "lock",
            "locked?",
            "owned?",
            "sleep",
            "synchronize",
            "try_lock",
            "unlock",
        ],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Thread::Queue",
        public: &[
            "<<",
            "clear",
            "close",
            "closed?",
            "deq",
            "empty?",
            "enq",
            "freeze",
            "length",
            "marshal_dump",
            "num_waiting",
            "pop",
            "push",
            "shift",
            "size",
        ],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Thread::SizedQueue",
        public: &[
            "<<",
            "clear",
            "close",
            "deq",
            "enq",
            "max",
            "max=",
            "num_waiting",
            "pop",
            "push",
            "shift",
        ],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "ThreadGroup",
        public: &["add", "enclose", "enclosed?", "list"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "Time",
        public: &[
            "+",
            "-",
            "<=>",
            "asctime",
            "ceil",
            "ctime",
            "day",
            "deconstruct_keys",
            "dst?",
            "eql?",
            "floor",
            "friday?",
            "getgm",
            "getlocal",
            "getutc",
            "gmt?",
            "gmt_offset",
            "gmtime",
            "gmtoff",
            "hash",
            "hour",
            "inspect",
            "isdst",
            "iso8601",
            "localtime",
            "mday",
            "min",
            "mon",
            "monday?",
            "month",
            "nsec",
            "round",
            "saturday?",
            "sec",
            "strftime",
            "subsec",
            "sunday?",
            "thursday?",
            "to_a",
            "to_f",
            "to_i",
            "to_r",
            "to_s",
            "tuesday?",
            "tv_nsec",
            "tv_sec",
            "tv_usec",
            "usec",
            "utc",
            "utc?",
            "utc_offset",
            "wday",
            "wednesday?",
            "xmlschema",
            "yday",
            "year",
            "zone",
        ],
        private: &["_dump", "initialize", "initialize_copy"],
        protected: &[],
    },
    CoreMethods {
        owner: "TracePoint",
        public: &[
            "binding",
            "callee_id",
            "defined_class",
            "disable",
            "enable",
            "enabled?",
            "eval_script",
            "event",
            "inspect",
            "instruction_sequence",
            "lineno",
            "method_id",
            "parameters",
            "path",
            "raised_exception",
            "return_value",
            "self",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "TrueClass",
        public: &["&", "===", "^", "inspect", "to_s", "|"],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "UnboundMethod",
        public: &[
            "==",
            "arity",
            "bind",
            "bind_call",
            "clone",
            "dup",
            "eql?",
            "hash",
            "inspect",
            "name",
            "original_name",
            "owner",
            "parameters",
            "source_location",
            "super_method",
            "to_s",
        ],
        private: &[],
        protected: &[],
    },
    CoreMethods {
        owner: "UncaughtThrowError",
        public: &["tag", "to_s", "value"],
        private: &["initialize"],
        protected: &[],
    },
    CoreMethods {
        owner: "Warning",
        public: &["warn"],
        private: &[],
        protected: &[],
    },
];
