// The methods core classes answer through native dispatch rather than a
// method table, by the class or module Ruby defines each in.

use super::*;

/// Each class or module with the names of the methods metorex answers for
/// it natively, which `respond_to?` and `defined?` report.
const NATIVE_METHODS_BY_OWNER: &[(&str, &[&str])] = &[
    (
        "Array",
        &[
            "&",
            "*",
            "+",
            "-",
            "<<",
            "<=>",
            "[]=",
            "assoc",
            "at",
            "clear",
            "collect!",
            "compact!",
            "concat",
            "delete",
            "delete_at",
            "delete_if",
            "difference",
            "dig",
            "each",
            "each_index",
            "empty?",
            "fetch",
            "fetch_values",
            "filter!",
            "flatten",
            "flatten!",
            "index",
            "insert",
            "intersect?",
            "intersection",
            "join",
            "keep_if",
            "last",
            "map!",
            "pack",
            "prepend",
            "rassoc",
            "reject!",
            "replace",
            "reverse",
            "reverse!",
            "rindex",
            "rotate",
            "rotate!",
            "sample",
            "select!",
            "shift",
            "shuffle",
            "shuffle!",
            "size",
            "slice",
            "slice!",
            "sort!",
            "sort_by!",
            "to_ary",
            "transpose",
            "union",
            "uniq!",
            "unshift",
            "values_at",
            "|",
        ],
    ),
    ("BasicObject", &["instance_eval", "instance_exec"]),
    ("Comparable", &["<", "<=", ">", ">=", "between?", "clamp"]),
    (
        "Complex",
        &[
            "*",
            "**",
            "+",
            "-",
            "/",
            "<=>",
            "rationalize",
            "to_f",
            "to_i",
            "to_r",
        ],
    ),
    ("FalseClass", &["&", "===", "^", "inspect", "to_s", "|"]),
    (
        "Float",
        &[
            "*",
            "**",
            "+",
            "-",
            "/",
            "<",
            "<=",
            "<=>",
            ">",
            ">=",
            "nan?",
            "next_float",
            "prev_float",
            "to_f",
            "to_i",
            "to_r",
        ],
    ),
    (
        "Hash",
        &[
            "<",
            "<=",
            ">",
            ">=",
            "[]=",
            "assoc",
            "clear",
            "compact!",
            "compare_by_identity",
            "compare_by_identity?",
            "default",
            "default=",
            "default_proc",
            "default_proc=",
            "delete",
            "delete_if",
            "dig",
            "each",
            "each_key",
            "each_pair",
            "each_value",
            "empty?",
            "except",
            "fetch",
            "fetch_values",
            "filter!",
            "flatten",
            "has_value?",
            "invert",
            "keep_if",
            "key",
            "key?",
            "merge",
            "merge!",
            "rassoc",
            "rehash",
            "reject!",
            "replace",
            "select!",
            "shift",
            "slice",
            "store",
            "to_hash",
            "transform_keys",
            "transform_keys!",
            "transform_values",
            "transform_values!",
            "update",
            "value?",
            "values_at",
        ],
    ),
    (
        "Integer",
        &[
            "&",
            "<",
            "<<",
            "<=",
            ">",
            ">=",
            ">>",
            "[]",
            "^",
            "allbits?",
            "anybits?",
            "bit_length",
            "ceildiv",
            "chr",
            "digits",
            "gcd",
            "gcdlcm",
            "lcm",
            "nobits?",
            "ord",
            "|",
            "~",
        ],
    ),
    (
        "Kernel",
        &[
            "<=>",
            "private_methods",
            "protected_methods",
            "public_methods",
        ],
    ),
    (
        "NilClass",
        &[
            "&",
            "===",
            "=~",
            "^",
            "inspect",
            "nil?",
            "rationalize",
            "to_a",
            "to_c",
            "to_f",
            "to_h",
            "to_i",
            "to_r",
            "to_s",
            "|",
        ],
    ),
    ("Range", &["bsearch", "overlap?"]),
    (
        "Rational",
        &["*", "**", "+", "-", "/", "<=>", "to_f", "to_i", "to_r"],
    ),
    ("Regexp", &["encoding", "fixed_encoding?", "timeout", "~"]),
    (
        "String",
        &[
            "%",
            "*",
            "+@",
            "-@",
            "<=>",
            "=~",
            "[]",
            "ascii_only?",
            "b",
            "byteindex",
            "byterindex",
            "bytesize",
            "byteslice",
            "capitalize",
            "casecmp",
            "casecmp?",
            "center",
            "chomp",
            "chop",
            "chr",
            "codepoints",
            "count",
            "crypt",
            "dedup",
            "delete",
            "delete_prefix",
            "delete_suffix",
            "dump",
            "each_byte",
            "each_char",
            "each_codepoint",
            "each_grapheme_cluster",
            "each_line",
            "empty?",
            "encode",
            "encoding",
            "end_with?",
            "force_encoding",
            "getbyte",
            "grapheme_clusters",
            "gsub",
            "hex",
            "include?",
            "index",
            "intern",
            "lines",
            "ljust",
            "lstrip",
            "match",
            "match?",
            "oct",
            "ord",
            "partition",
            "rindex",
            "rjust",
            "rpartition",
            "rstrip",
            "scan",
            "scrub",
            "slice",
            "split",
            "squeeze",
            "start_with?",
            "strip",
            "sub",
            "sum",
            "swapcase",
            "to_c",
            "to_f",
            "to_i",
            "to_r",
            "to_sym",
            "tr",
            "tr_s",
            "undump",
            "unicode_normalize",
            "unicode_normalized?",
            "unpack",
            "unpack1",
            "upto",
            "valid_encoding?",
        ],
    ),
    (
        "Struct",
        &[
            "[]",
            "[]=",
            "deconstruct",
            "deconstruct_keys",
            "dig",
            "each",
            "each_pair",
            "length",
            "members",
            "size",
            "values",
            "values_at",
        ],
    ),
    (
        "Symbol",
        &[
            "<=>",
            "=~",
            "[]",
            "capitalize",
            "casecmp",
            "casecmp?",
            "downcase",
            "empty?",
            "encoding",
            "end_with?",
            "id2name",
            "intern",
            "length",
            "match",
            "match?",
            "name",
            "size",
            "slice",
            "start_with?",
            "swapcase",
            "to_proc",
            "to_sym",
            "upcase",
        ],
    ),
    ("TrueClass", &["&", "===", "^", "inspect", "to_s", "|"]),
];

/// Whether the class or module named `owner` answers `name` natively.
fn owner_answers(owner: &str, name: &str) -> bool {
    NATIVE_METHODS_BY_OWNER
        .iter()
        .any(|(held, names)| *held == owner && names.contains(&name))
}

/// Whether nil, true or false answers `name` with a native method of its own
/// class, as against one every object has.
pub(crate) fn value_answers_natively(receiver: &Object, name: &str) -> bool {
    crate::builtin_classes::value_class_name(receiver)
        .is_some_and(|named| owner_answers(named, name))
}

/// Whether instances of `class` answer `name` natively: by the class
/// itself, a module it mixes in, or, when `inherited`, a class above it.
/// Object carries what Kernel and BasicObject answer.
pub(crate) fn class_answers_natively(class: &Rc<Class>, name: &str, inherited: bool) -> bool {
    let mut cursor = Some(Rc::clone(class));
    while let Some(current) = cursor {
        let named = current.ruby_name();
        if owner_answers(&named, name)
            || (named == "Object"
                && (owner_answers("Kernel", name) || owner_answers("BasicObject", name)))
            || current
                .transitive_mixins()
                .iter()
                .any(|mixin| owner_answers(&mixin.ruby_name(), name))
        {
            return true;
        }
        if !inherited {
            return false;
        }
        cursor = current.superclass();
    }
    false
}

impl VirtualMachine {
    /// Whether `receiver` answers `name` through native dispatch.
    pub(crate) fn answers_natively(&self, receiver: &Object, name: &str) -> bool {
        // nil, true and false share Object's class record, so their own
        // class is asked by name first.
        crate::builtin_classes::value_class_name(receiver)
            .is_some_and(|named| owner_answers(named, name))
            || class_answers_natively(&self.builtins().class_of(receiver), name, true)
    }
}
