puts("hello %s" % "world")
puts("num: %d" % 42)
puts("pi: %.2f" % 3.14159)
puts("hex: %x" % 255)
puts("%s has %d items" % ["cart", 5])
puts("100%% complete: %s" % "done")
puts("%p" % "test")
puts("%05d" % 42)
puts("%-10s|" % "left")
