// Every `Errno::EXXX` class the platform names.

use super::*;

/// Where an Errno class keeps the message its number stands for.
pub(crate) const ERRNO_MESSAGE_KEY: &str = "__errno_message__";

/// Every `Errno::EXXX` class the platform names, each a subclass of
/// SystemCallError carrying its own number in an `Errno` constant. The numbers
/// and the names come from libc rather than a table, since they differ between
/// Linux and macOS.
pub(crate) fn register_errno_classes(errno_module: &Rc<Class>, system_call_error: &Rc<Class>) {
    #[cfg(target_os = "macos")]
    const ERRNO_NUMBERS: &[(&str, i32)] = &[
        ("EPERM", libc::EPERM),
        ("ENOENT", libc::ENOENT),
        ("ESRCH", libc::ESRCH),
        ("EINTR", libc::EINTR),
        ("EIO", libc::EIO),
        ("ENXIO", libc::ENXIO),
        ("E2BIG", libc::E2BIG),
        ("ENOEXEC", libc::ENOEXEC),
        ("EBADF", libc::EBADF),
        ("ECHILD", libc::ECHILD),
        ("EDEADLK", libc::EDEADLK),
        ("ENOMEM", libc::ENOMEM),
        ("EACCES", libc::EACCES),
        ("EFAULT", libc::EFAULT),
        ("ENOTBLK", libc::ENOTBLK),
        ("EBUSY", libc::EBUSY),
        ("EEXIST", libc::EEXIST),
        ("EXDEV", libc::EXDEV),
        ("ENODEV", libc::ENODEV),
        ("ENOTDIR", libc::ENOTDIR),
        ("EISDIR", libc::EISDIR),
        ("EINVAL", libc::EINVAL),
        ("ENFILE", libc::ENFILE),
        ("EMFILE", libc::EMFILE),
        ("ENOTTY", libc::ENOTTY),
        ("ETXTBSY", libc::ETXTBSY),
        ("EFBIG", libc::EFBIG),
        ("ENOSPC", libc::ENOSPC),
        ("ESPIPE", libc::ESPIPE),
        ("EROFS", libc::EROFS),
        ("EMLINK", libc::EMLINK),
        ("EPIPE", libc::EPIPE),
        ("EDOM", libc::EDOM),
        ("ERANGE", libc::ERANGE),
        ("EAGAIN", libc::EAGAIN),
        ("EINPROGRESS", libc::EINPROGRESS),
        ("EALREADY", libc::EALREADY),
        ("ENOTSOCK", libc::ENOTSOCK),
        ("EDESTADDRREQ", libc::EDESTADDRREQ),
        ("EMSGSIZE", libc::EMSGSIZE),
        ("EPROTOTYPE", libc::EPROTOTYPE),
        ("ENOPROTOOPT", libc::ENOPROTOOPT),
        ("EPROTONOSUPPORT", libc::EPROTONOSUPPORT),
        ("ESOCKTNOSUPPORT", libc::ESOCKTNOSUPPORT),
        ("ENOTSUP", libc::ENOTSUP),
        ("EPFNOSUPPORT", libc::EPFNOSUPPORT),
        ("EAFNOSUPPORT", libc::EAFNOSUPPORT),
        ("EADDRINUSE", libc::EADDRINUSE),
        ("EADDRNOTAVAIL", libc::EADDRNOTAVAIL),
        ("ENETDOWN", libc::ENETDOWN),
        ("ENETUNREACH", libc::ENETUNREACH),
        ("ENETRESET", libc::ENETRESET),
        ("ECONNABORTED", libc::ECONNABORTED),
        ("ECONNRESET", libc::ECONNRESET),
        ("ENOBUFS", libc::ENOBUFS),
        ("EISCONN", libc::EISCONN),
        ("ENOTCONN", libc::ENOTCONN),
        ("ESHUTDOWN", libc::ESHUTDOWN),
        ("ETOOMANYREFS", libc::ETOOMANYREFS),
        ("ETIMEDOUT", libc::ETIMEDOUT),
        ("ECONNREFUSED", libc::ECONNREFUSED),
        ("ELOOP", libc::ELOOP),
        ("ENAMETOOLONG", libc::ENAMETOOLONG),
        ("EHOSTDOWN", libc::EHOSTDOWN),
        ("EHOSTUNREACH", libc::EHOSTUNREACH),
        ("ENOTEMPTY", libc::ENOTEMPTY),
        ("EPROCLIM", libc::EPROCLIM),
        ("EUSERS", libc::EUSERS),
        ("EDQUOT", libc::EDQUOT),
        ("ESTALE", libc::ESTALE),
        ("EREMOTE", libc::EREMOTE),
        ("EBADRPC", libc::EBADRPC),
        ("ERPCMISMATCH", libc::ERPCMISMATCH),
        ("EPROGUNAVAIL", libc::EPROGUNAVAIL),
        ("EPROGMISMATCH", libc::EPROGMISMATCH),
        ("EPROCUNAVAIL", libc::EPROCUNAVAIL),
        ("ENOLCK", libc::ENOLCK),
        ("ENOSYS", libc::ENOSYS),
        ("EFTYPE", libc::EFTYPE),
        ("EAUTH", libc::EAUTH),
        ("ENEEDAUTH", libc::ENEEDAUTH),
        ("EPWROFF", libc::EPWROFF),
        ("EDEVERR", libc::EDEVERR),
        ("EOVERFLOW", libc::EOVERFLOW),
        ("EBADEXEC", libc::EBADEXEC),
        ("EBADARCH", libc::EBADARCH),
        ("ESHLIBVERS", libc::ESHLIBVERS),
        ("EBADMACHO", libc::EBADMACHO),
        ("ECANCELED", libc::ECANCELED),
        ("EIDRM", libc::EIDRM),
        ("ENOMSG", libc::ENOMSG),
        ("EILSEQ", libc::EILSEQ),
        ("ENOATTR", libc::ENOATTR),
        ("EBADMSG", libc::EBADMSG),
        ("EMULTIHOP", libc::EMULTIHOP),
        ("ENODATA", libc::ENODATA),
        ("ENOLINK", libc::ENOLINK),
        ("ENOSR", libc::ENOSR),
        ("ENOSTR", libc::ENOSTR),
        ("EPROTO", libc::EPROTO),
        ("ETIME", libc::ETIME),
        ("EOPNOTSUPP", libc::EOPNOTSUPP),
        ("ENOPOLICY", libc::ENOPOLICY),
        ("ENOTRECOVERABLE", libc::ENOTRECOVERABLE),
        ("EOWNERDEAD", libc::EOWNERDEAD),
        ("EQFULL", libc::EQFULL),
    ];
    #[cfg(not(target_os = "macos"))]
    const ERRNO_NUMBERS: &[(&str, i32)] = &[
        ("EPERM", libc::EPERM),
        ("ENOENT", libc::ENOENT),
        ("ESRCH", libc::ESRCH),
        ("EINTR", libc::EINTR),
        ("EIO", libc::EIO),
        ("ENXIO", libc::ENXIO),
        ("E2BIG", libc::E2BIG),
        ("ENOEXEC", libc::ENOEXEC),
        ("EBADF", libc::EBADF),
        ("ECHILD", libc::ECHILD),
        ("EAGAIN", libc::EAGAIN),
        ("ENOMEM", libc::ENOMEM),
        ("EACCES", libc::EACCES),
        ("EFAULT", libc::EFAULT),
        ("ENOTBLK", libc::ENOTBLK),
        ("EBUSY", libc::EBUSY),
        ("EEXIST", libc::EEXIST),
        ("EXDEV", libc::EXDEV),
        ("ENODEV", libc::ENODEV),
        ("ENOTDIR", libc::ENOTDIR),
        ("EISDIR", libc::EISDIR),
        ("EINVAL", libc::EINVAL),
        ("ENFILE", libc::ENFILE),
        ("EMFILE", libc::EMFILE),
        ("ENOTTY", libc::ENOTTY),
        ("ETXTBSY", libc::ETXTBSY),
        ("EFBIG", libc::EFBIG),
        ("ENOSPC", libc::ENOSPC),
        ("ESPIPE", libc::ESPIPE),
        ("EROFS", libc::EROFS),
        ("EMLINK", libc::EMLINK),
        ("EPIPE", libc::EPIPE),
        ("EDOM", libc::EDOM),
        ("ERANGE", libc::ERANGE),
        ("EDEADLK", libc::EDEADLK),
        ("ENAMETOOLONG", libc::ENAMETOOLONG),
        ("ENOLCK", libc::ENOLCK),
        ("ENOSYS", libc::ENOSYS),
        ("ENOTEMPTY", libc::ENOTEMPTY),
        ("ELOOP", libc::ELOOP),
        ("ENOMSG", libc::ENOMSG),
        ("EIDRM", libc::EIDRM),
        ("ECHRNG", libc::ECHRNG),
        ("EL2NSYNC", libc::EL2NSYNC),
        ("EL3HLT", libc::EL3HLT),
        ("EL3RST", libc::EL3RST),
        ("ELNRNG", libc::ELNRNG),
        ("EUNATCH", libc::EUNATCH),
        ("ENOCSI", libc::ENOCSI),
        ("EL2HLT", libc::EL2HLT),
        ("EBADE", libc::EBADE),
        ("EBADR", libc::EBADR),
        ("EXFULL", libc::EXFULL),
        ("ENOANO", libc::ENOANO),
        ("EBADRQC", libc::EBADRQC),
        ("EBADSLT", libc::EBADSLT),
        ("EBFONT", libc::EBFONT),
        ("ENOSTR", libc::ENOSTR),
        ("ENODATA", libc::ENODATA),
        ("ETIME", libc::ETIME),
        ("ENOSR", libc::ENOSR),
        ("ENONET", libc::ENONET),
        ("ENOPKG", libc::ENOPKG),
        ("EREMOTE", libc::EREMOTE),
        ("ENOLINK", libc::ENOLINK),
        ("EADV", libc::EADV),
        ("ESRMNT", libc::ESRMNT),
        ("ECOMM", libc::ECOMM),
        ("EPROTO", libc::EPROTO),
        ("EMULTIHOP", libc::EMULTIHOP),
        ("EDOTDOT", libc::EDOTDOT),
        ("EBADMSG", libc::EBADMSG),
        ("EOVERFLOW", libc::EOVERFLOW),
        ("ENOTUNIQ", libc::ENOTUNIQ),
        ("EBADFD", libc::EBADFD),
        ("EREMCHG", libc::EREMCHG),
        ("ELIBACC", libc::ELIBACC),
        ("ELIBBAD", libc::ELIBBAD),
        ("ELIBSCN", libc::ELIBSCN),
        ("ELIBMAX", libc::ELIBMAX),
        ("ELIBEXEC", libc::ELIBEXEC),
        ("EILSEQ", libc::EILSEQ),
        ("ERESTART", libc::ERESTART),
        ("ESTRPIPE", libc::ESTRPIPE),
        ("EUSERS", libc::EUSERS),
        ("ENOTSOCK", libc::ENOTSOCK),
        ("EDESTADDRREQ", libc::EDESTADDRREQ),
        ("EMSGSIZE", libc::EMSGSIZE),
        ("EPROTOTYPE", libc::EPROTOTYPE),
        ("ENOPROTOOPT", libc::ENOPROTOOPT),
        ("EPROTONOSUPPORT", libc::EPROTONOSUPPORT),
        ("ESOCKTNOSUPPORT", libc::ESOCKTNOSUPPORT),
        ("EOPNOTSUPP", libc::EOPNOTSUPP),
        ("EPFNOSUPPORT", libc::EPFNOSUPPORT),
        ("EAFNOSUPPORT", libc::EAFNOSUPPORT),
        ("EADDRINUSE", libc::EADDRINUSE),
        ("EADDRNOTAVAIL", libc::EADDRNOTAVAIL),
        ("ENETDOWN", libc::ENETDOWN),
        ("ENETUNREACH", libc::ENETUNREACH),
        ("ENETRESET", libc::ENETRESET),
        ("ECONNABORTED", libc::ECONNABORTED),
        ("ECONNRESET", libc::ECONNRESET),
        ("ENOBUFS", libc::ENOBUFS),
        ("EISCONN", libc::EISCONN),
        ("ENOTCONN", libc::ENOTCONN),
        ("ESHUTDOWN", libc::ESHUTDOWN),
        ("ETOOMANYREFS", libc::ETOOMANYREFS),
        ("ETIMEDOUT", libc::ETIMEDOUT),
        ("ECONNREFUSED", libc::ECONNREFUSED),
        ("EHOSTDOWN", libc::EHOSTDOWN),
        ("EHOSTUNREACH", libc::EHOSTUNREACH),
        ("EALREADY", libc::EALREADY),
        ("EINPROGRESS", libc::EINPROGRESS),
        ("ESTALE", libc::ESTALE),
        ("EUCLEAN", libc::EUCLEAN),
        ("ENOTNAM", libc::ENOTNAM),
        ("ENAVAIL", libc::ENAVAIL),
        ("EISNAM", libc::EISNAM),
        ("EREMOTEIO", libc::EREMOTEIO),
        ("EDQUOT", libc::EDQUOT),
        ("ENOMEDIUM", libc::ENOMEDIUM),
        ("EMEDIUMTYPE", libc::EMEDIUMTYPE),
        ("ECANCELED", libc::ECANCELED),
        ("ENOKEY", libc::ENOKEY),
        ("EKEYEXPIRED", libc::EKEYEXPIRED),
        ("EKEYREVOKED", libc::EKEYREVOKED),
        ("EKEYREJECTED", libc::EKEYREJECTED),
        ("EOWNERDEAD", libc::EOWNERDEAD),
        ("ENOTRECOVERABLE", libc::ENOTRECOVERABLE),
        ("ERFKILL", libc::ERFKILL),
        ("EHWPOISON", libc::EHWPOISON),
    ];
    for (name, number) in ERRNO_NUMBERS {
        let class = Rc::new(Class::new(
            format!("Errno::{}", name),
            Some(Rc::clone(system_call_error)),
        ));
        class.set_class_var("Errno", Object::Int(*number as i64));
        // The message the errno stands for, which an instance reports when
        // no custom one is given. Kept under a mangled key so it does not
        // show up as a Ruby-visible constant.
        class.set_class_var(
            ERRNO_MESSAGE_KEY,
            Object::string(errno_description(*number)),
        );
        errno_module.set_class_var(*name, Object::Class(class));
    }
    // `Errno::NOERROR` stands for a successful call, which Ruby defines
    // alongside the numbered errors.
    let no_error = Rc::new(Class::new(
        "Errno::NOERROR",
        Some(Rc::clone(system_call_error)),
    ));
    no_error.set_class_var("Errno", Object::Int(0));
    no_error.set_class_var(ERRNO_MESSAGE_KEY, Object::string("Success".to_string()));
    errno_module.set_class_var("NOERROR", Object::Class(no_error));
    // Ruby aliases these where the platform gives them the same number.
    for (alias, canonical) in [
        ("EWOULDBLOCK", "EAGAIN"),
        ("ENOTSUP", "EOPNOTSUPP"),
        ("EDEADLOCK", "EDEADLK"),
    ] {
        if errno_module.get_class_var(alias).is_none()
            && let Some(existing) = errno_module.get_class_var(canonical)
        {
            errno_module.set_class_var(alias, existing);
        }
    }
}

/// What the C library calls the number, which is the message Ruby reports for
/// it. Rust renders an os error as "Invalid argument (os error 22)", and Ruby
/// reports only the first half.
pub(crate) fn errno_description(number: i32) -> String {
    let rendered = std::io::Error::from_raw_os_error(number).to_string();
    match rendered.rfind(" (os error ") {
        Some(cut) => rendered[..cut].to_string(),
        None => rendered,
    }
}
