# Writes src/vm/stdlib/parser_tables.rb from the parse.c of a Ruby release:
# the LALR tables MRI's parser runs on, the number of each token, and the
# name a syntax error gives each one. The Ripper grammar replays the tokens
# of a program it refuses through these tables to word the error as MRI's
# parser does.
#
#   ruby scripts/generate_parser_tables.rb path/to/parse.c
#
# A release tarball, such as ruby-4.0.6.tar.gz from cache.ruby-lang.org,
# carries the generated parse.c.

abort "usage: ruby scripts/generate_parser_tables.rb path/to/parse.c" unless ARGV[0]

source = File.read(ARGV[0])
root = File.expand_path("..", __dir__)

def table(source, name)
  body = source[/static const yytype_\w+ #{name}\[\] =\s*\{(.*?)\};/m, 1]
  abort "no #{name} table" unless body
  body.scan(/-?\d+/).map(&:to_i)
end

def define(source, name)
  value = source[/#define #{name}\s+\(?(-?\d+)\)?/, 1]
  abort "no #{name}" unless value
  value.to_i
end

tokens = define(source, "YYNTOKENS")

# The number of each token, keyed by the name parse.y declares it under, or
# by its quoted character for a token of one character.
numbers = {}
source[/enum yysymbol_kind_t\s*\{(.*?)\};/m, 1].scan(%r{YYSYMBOL_(\w+) = (\d+),\s*/\* (.*?)  \*/}) do |name, number, comment|
  number = number.to_i
  next unless number < tokens

  key = name.match?(/\A\d+_/) ? comment : name
  numbers[key] = number
end

# The name an error message gives a token, which MRI's parser takes from
# the string parse.y declares it with, with the quotes around it removed.
names = source[/static const char \*const yytname\[\] =\s*\{(.*?)\};/m, 1]
  .scan(/"((?:[^"\\]|\\.)*)"/).flatten.first(tokens).map do |literal|
    text = literal.gsub(/\\(.)/) { Regexp.last_match(1) }
    text.start_with?('"') && text.end_with?('"') && !text.include?(",") ? text[1...-1] : text
  end

packed = lambda do |values|
  [values.pack("s<*")].pack("m0")
end

revision = File.read(File.join(File.dirname(ARGV[0]), "revision.h"))[/RUBY_FULL_REVISION "(\w+)"/, 1] rescue nil

File.open(File.join(root, "src", "vm", "stdlib", "parser_tables.rb"), "w") do |out|
  out.puts "# The LALR tables of MRI's parser, generated by"
  out.puts "# scripts/generate_parser_tables.rb from the parse.c of Ruby revision"
  out.puts "# #{revision || "(unknown)"}. Do not edit."
  out.puts
  out.puts "class Ripper"
  out.puts "  module Engine"
  out.puts "    module ParserTables"
  %w[YYFINAL YYLAST YYNTOKENS YYPACT_NINF YYTABLE_NINF].each do |name|
    out.puts "      #{name.delete_prefix("YY")} = #{define(source, name)}"
  end
  %w[yypact yydefact yypgoto yydefgoto yytable yycheck yyr1 yyr2].each do |name|
    out.puts "      #{name.delete_prefix("yy").upcase} = #{packed.call(table(source, name)).inspect}.unpack1(\"m0\").unpack(\"s<*\").freeze"
  end
  out.puts "      NUMBERS = {"
  numbers.each { |key, number| out.puts "        #{key.inspect} => #{number}," }
  out.puts "      }.freeze"
  out.puts "      NAMES = ["
  names.each { |name| out.puts "        #{name.inspect}," }
  out.puts "      ].freeze"
  out.puts "    end"
  out.puts "  end"
  out.puts "end"
end
