# Writes src/vm/init/encoding_table.rs from the Ruby running the script: the
# encodings it defines in the order `Encoding.list` gives them, whether each
# is a dummy, the constants that name each one, and the aliases that stand
# for one. Run it with the MRI release metorex follows.
#
#   ruby scripts/generate_encoding_table.rb

root = File.expand_path("..", __dir__)
# The aliases that follow the settings of the running process, which
# metorex answers from its own settings.
settings = %w[external locale filesystem]

constants = Encoding.constants.sort.filter_map do |name|
  held = Encoding.const_get(name)
  [name.to_s, held] if held.is_a?(Encoding)
end
ordered = Encoding.list.each_with_index.flat_map do |encoding, index|
  constants.select { |_, held| held == encoding }.map { |name, _| [name, encoding, index] }
end
aliases = Encoding.aliases.reject { |name, _| settings.include?(name) }
lines = []
lines << "// The encodings, constants and aliases of Ruby #{RUBY_VERSION}, generated by"
lines << "// scripts/generate_encoding_table.rb. Do not edit."
lines << ""
lines << "/// Each constant naming an encoding, with the encoding's name and whether"
lines << "/// it is a dummy, in the order `Encoding.list` gives the encodings."
lines << "pub(crate) const ENCODING_NAMES: [(&str, &str, bool); #{ordered.size}] = ["
ordered.each { |name, encoding, _| lines << "    (#{name.inspect}, #{encoding.name.inspect}, #{encoding.dummy?})," }
lines << "];"
lines << ""
lines << "/// Each alias with the name of the encoding it stands for, in the order"
lines << "/// `Encoding.aliases` gives them."
lines << "pub(crate) const ENCODING_ALIASES: [(&str, &str); #{aliases.size}] = ["
aliases.each { |name, target| lines << "    (#{name.inspect}, #{target.inspect})," }
lines << "];"
named = Encoding.name_list - settings - ["internal"]
lines << ""
lines << "/// Every name and alias in the order `Encoding.name_list` gives them, the"
lines << "/// names that follow the settings left out."
lines << "pub(crate) const ENCODING_NAME_LIST: [&str; #{named.size}] = ["
named.each { |name| lines << "    #{name.inspect}," }
lines << "];"
File.write(File.join(root, "src", "vm", "init", "encoding_table.rs"), lines.join("\n") + "\n")
