#!/usr/bin/env bash

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
METOREX="$REPO_ROOT/target/debug/metorex"
MSPEC="$REPO_ROOT/ruby/mspec/bin/mspec"
SPEC_DIR="$REPO_ROOT/ruby/spec"

if [ ! -f "$METOREX" ]; then
  echo "Building metorex..."
  cargo build --manifest-path "$REPO_ROOT/Cargo.toml"
fi

# Passing specs - add new lines as specs reach a passing state

# 4.1 - 4.3: Primitives and Singletons
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/true"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/nil"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/false"

# 4.4 - 4.9: Core Classes and Modules
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/comparable"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/main/to_s_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/main/define_method_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/main/include_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/main/private_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/main/public_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/main/ruby2_keywords_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/main/using_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/class/allocate_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/class/attached_object_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/class/dup_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/class/inherited_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/class/initialize_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/class/new_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/class/subclasses_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/class/superclass_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/alias_method_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/ancestors_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/append_features_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/attr_accessor_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/attr_reader_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/attr_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/attr_writer_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/autoload_relative_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/autoload_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/case_compare_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/class_eval_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/class_exec_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/class_variable_defined_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/class_variable_get_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/class_variable_set_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/class_variables_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/comparison_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/const_added_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/const_defined_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/const_get_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/const_missing_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/const_set_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/const_source_location_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/constants_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/define_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/define_singleton_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/deprecate_constant_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/eql_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/equal_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/equal_value_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/extend_object_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/extended_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/freeze_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/gt_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/gte_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/include_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/included_modules_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/included_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/initialize_copy_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/initialize_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/instance_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/instance_methods_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/lt_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/lte_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/method_added_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/method_defined_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/method_removed_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/method_undefined_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/module_eval_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/module_exec_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/module_function_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/name_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/nesting_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/new_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/prepend_features_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/prepend_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/prepended_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/private_class_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/private_constant_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/private_instance_methods_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/private_method_defined_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/private_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/protected_instance_methods_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/protected_method_defined_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/protected_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/public_class_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/public_constant_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/public_instance_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/public_instance_methods_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/public_method_defined_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/public_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/refine_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/refinements_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/remove_class_variable_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/remove_const_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/remove_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/ruby2_keywords_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/set_temporary_name_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/singleton_class_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/to_s_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/undef_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/undefined_instance_methods_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/used_refinements_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/module/using_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/Array_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/Complex_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/Float_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/Hash_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/Integer_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/Rational_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/String_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/__callee___spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/__dir___spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/__method___spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/abort_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/at_exit_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/autoload_relative_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/autoload_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/backtick_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/binding_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/block_given_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/caller_locations_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/caller_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/case_compare_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/catch_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/chomp_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/chop_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/class_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/clone_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/comparison_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/define_singleton_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/display_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/dup_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/enum_for_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/eql_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/equal_value_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/eval_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/exec_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/exit_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/extend_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/fail_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/fork_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/format_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/freeze_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/frozen_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/gets_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/global_variables_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/gsub_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/initialize_clone_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/initialize_copy_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/initialize_dup_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/inspect_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/instance_of_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/instance_variable_defined_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/instance_variable_get_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/instance_variable_set_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/instance_variables_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/is_a_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/itself_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/kind_of_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/lambda_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/load_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/local_variables_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/loop_spec.rb"
"$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/match_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/methods_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/nil_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/not_match_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/object_id_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/open_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/p_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/pp_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/print_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/printf_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/private_methods_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/proc_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/protected_methods_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/public_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/public_methods_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/public_send_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/putc_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/puts_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/raise_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/rand_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/readline_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/readlines_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/remove_instance_variable_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/require_relative_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/require_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/respond_to_missing_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/respond_to_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/select_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/send_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/set_trace_func_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/singleton_class_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/singleton_method_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/singleton_methods_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/sleep_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/spawn_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/sprintf_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/srand_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/sub_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/syscall_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/system_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/taint_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/tainted_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/tap_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/test_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/then_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/throw_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/to_enum_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/to_s_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/trace_var_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/trap_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/trust_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/untaint_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/untrace_var_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/untrust_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/untrusted_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/warn_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/kernel/yield_self_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/__id__spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/__send___spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/basicobject_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/equal_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/equal_value_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/initialize_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/instance_eval_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/instance_exec_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/method_missing_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/not_equal_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/not_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/singleton_method_added_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/singleton_method_removed_spec.rb"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/basicobject/singleton_method_undefined_spec.rb"

# 4.10 - 4.13: Exceptions and Signals
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/exception"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/systemexit"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/signal"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/warning"

# 4.14 - 4.19: Numeric Types
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/integer"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/float"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/numeric"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/complex"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/rational"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/math"

# 4.20 - 4.25: Collections
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/array"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/hash"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/set"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/range"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/struct"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/data"

# 4.26 - 4.30: Strings and Patterns
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/string"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/symbol"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/regexp"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/encoding"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/matchdata"

# 4.31 - 4.34: Callables and Introspection
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/proc"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/method"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/unboundmethod"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/binding"

# 4.35 - 4.39: IO and Filesystem
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/io"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/file"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/dir"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/filetest"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/env"

# 4.40 - 4.46: Concurrency
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/thread"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/fiber"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/mutex"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/conditionvariable"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/queue"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/sizedqueue"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/threadgroup"

# 4.47 - 4.55: Other
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/gc"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/objectspace"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/random"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/time"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/process"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/marshal"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/tracepoint"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/refinement"
# "$MSPEC" -t "$METOREX" "$SPEC_DIR/core/builtin_constants"
