#!/usr/bin/env bash

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
METOREX="$REPO_ROOT/target/debug/metorex"
MSPEC="$REPO_ROOT/ruby/mspec/bin/mspec"
SPEC_DIR="$REPO_ROOT/ruby/spec"

# mspec's ruby_exe helper resolves an interpreter at load time and raises when
# it finds none. Point it at metorex so loading succeeds; specs that shell out
# to a subprocess stay commented out regardless.
export RUBY_EXE="$METOREX"

if [ ! -f "$METOREX" ]; then
  echo "Building metorex..."
  cargo build --manifest-path "$REPO_ROOT/Cargo.toml"
fi

# Concurrency for the parallel spec runner. Defaults to the CPU count so a
# fresh checkout uses all cores; override with `JOBS=1 …` for a strictly
# sequential run when debugging interleaving issues.
JOBS="${JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)}"

# Aggregate counts. Updated after the parallel run drains, then printed by
# the EXIT trap so partial totals still surface if something blows up.
TOTAL_FILES=0
TOTAL_EXAMPLES=0
TOTAL_EXPECTATIONS=0
TOTAL_FAILURES=0
TOTAL_ERRORS=0
TOTAL_TAGGED=0
ANY_FAILED=0

# Use an explicit XXXXXX template so this works on both BSD mktemp (macOS,
# where `-t` is a prefix) and GNU mktemp (Linux/CI, where `-t` requires a
# template with X placeholders).
WORK_DIR=$(mktemp -d -t metorex_specs.XXXXXX)
# Scratch files the specs themselves write. mspec puts them under the working
# directory unless SPEC_TEMP_DIR names somewhere else, and a run that dies
# before its at_exit hook leaves what it wrote behind, so it goes in the
# operating system's temp directory rather than the checkout.
SPEC_TEMP_ROOT=$(mktemp -d -t metorex_spec_files.XXXXXX)
cleanup_workdir() { rm -rf "$WORK_DIR" "$SPEC_TEMP_ROOT"; }

print_totals() {
  printf '\n%s files, %s examples, %s expectations, %s failures, %s errors, %s tagged\n' \
    "$TOTAL_FILES" "$TOTAL_EXAMPLES" "$TOTAL_EXPECTATIONS" \
    "$TOTAL_FAILURES" "$TOTAL_ERRORS" "$TOTAL_TAGGED"
}
trap 'print_totals; cleanup_workdir' EXIT

# `run_spec` only queues — actual mspec invocations happen in parallel after
# the queue is fully populated. Indexed via a counter so output ordering
# below stays deterministic regardless of which worker finishes first.
SPEC_COUNT=0
SPEC_PATHS=()
run_spec() {
  SPEC_PATHS[$SPEC_COUNT]="$1"
  SPEC_COUNT=$((SPEC_COUNT + 1))
}

# Passing specs - add new lines as specs reach a passing state

# 4.1 - 4.3: Primitives and Singletons
run_spec "$SPEC_DIR/core/true"
run_spec "$SPEC_DIR/core/nil"
run_spec "$SPEC_DIR/core/false"

# 4.4 - 4.9: Core Classes and Modules
run_spec "$SPEC_DIR/core/comparable"
run_spec "$SPEC_DIR/core/main/define_method_spec.rb"
run_spec "$SPEC_DIR/core/main/include_spec.rb"
run_spec "$SPEC_DIR/core/main/private_spec.rb"
run_spec "$SPEC_DIR/core/main/public_spec.rb"
run_spec "$SPEC_DIR/core/main/ruby2_keywords_spec.rb"
run_spec "$SPEC_DIR/core/main/to_s_spec.rb"
run_spec "$SPEC_DIR/core/main/using_spec.rb"
run_spec "$SPEC_DIR/core/class/allocate_spec.rb"
run_spec "$SPEC_DIR/core/class/attached_object_spec.rb"
run_spec "$SPEC_DIR/core/class/dup_spec.rb"
run_spec "$SPEC_DIR/core/class/inherited_spec.rb"
run_spec "$SPEC_DIR/core/class/initialize_spec.rb"
run_spec "$SPEC_DIR/core/class/new_spec.rb"
run_spec "$SPEC_DIR/core/class/subclasses_spec.rb"
run_spec "$SPEC_DIR/core/class/superclass_spec.rb"
run_spec "$SPEC_DIR/core/module/alias_method_spec.rb"
run_spec "$SPEC_DIR/core/module/ancestors_spec.rb"
run_spec "$SPEC_DIR/core/module/append_features_spec.rb"
run_spec "$SPEC_DIR/core/module/attr_accessor_spec.rb"
run_spec "$SPEC_DIR/core/module/attr_reader_spec.rb"
run_spec "$SPEC_DIR/core/module/attr_spec.rb"
run_spec "$SPEC_DIR/core/module/attr_writer_spec.rb"
run_spec "$SPEC_DIR/core/module/autoload_relative_spec.rb"
run_spec "$SPEC_DIR/core/module/autoload_spec.rb"
run_spec "$SPEC_DIR/core/module/case_compare_spec.rb"
run_spec "$SPEC_DIR/core/module/class_eval_spec.rb"
run_spec "$SPEC_DIR/core/module/class_exec_spec.rb"
run_spec "$SPEC_DIR/core/module/class_variable_defined_spec.rb"
run_spec "$SPEC_DIR/core/module/class_variable_get_spec.rb"
run_spec "$SPEC_DIR/core/module/class_variable_set_spec.rb"
run_spec "$SPEC_DIR/core/module/class_variables_spec.rb"
run_spec "$SPEC_DIR/core/module/comparison_spec.rb"
run_spec "$SPEC_DIR/core/module/const_added_spec.rb"
run_spec "$SPEC_DIR/core/module/const_defined_spec.rb"
run_spec "$SPEC_DIR/core/module/const_get_spec.rb"
run_spec "$SPEC_DIR/core/module/const_missing_spec.rb"
run_spec "$SPEC_DIR/core/module/const_set_spec.rb"
run_spec "$SPEC_DIR/core/module/const_source_location_spec.rb"
run_spec "$SPEC_DIR/core/module/constants_spec.rb"
run_spec "$SPEC_DIR/core/module/define_method_spec.rb"
run_spec "$SPEC_DIR/core/module/define_singleton_method_spec.rb"
run_spec "$SPEC_DIR/core/module/deprecate_constant_spec.rb"
run_spec "$SPEC_DIR/core/module/eql_spec.rb"
run_spec "$SPEC_DIR/core/module/equal_spec.rb"
run_spec "$SPEC_DIR/core/module/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/module/extend_object_spec.rb"
run_spec "$SPEC_DIR/core/module/extended_spec.rb"
run_spec "$SPEC_DIR/core/module/freeze_spec.rb"
run_spec "$SPEC_DIR/core/module/gt_spec.rb"
run_spec "$SPEC_DIR/core/module/gte_spec.rb"
run_spec "$SPEC_DIR/core/module/include_spec.rb"
run_spec "$SPEC_DIR/core/module/included_modules_spec.rb"
run_spec "$SPEC_DIR/core/module/included_spec.rb"
run_spec "$SPEC_DIR/core/module/initialize_copy_spec.rb"
run_spec "$SPEC_DIR/core/module/initialize_spec.rb"
run_spec "$SPEC_DIR/core/module/instance_method_spec.rb"
run_spec "$SPEC_DIR/core/module/instance_methods_spec.rb"
run_spec "$SPEC_DIR/core/module/lt_spec.rb"
run_spec "$SPEC_DIR/core/module/lte_spec.rb"
run_spec "$SPEC_DIR/core/module/method_added_spec.rb"
run_spec "$SPEC_DIR/core/module/method_defined_spec.rb"
run_spec "$SPEC_DIR/core/module/method_removed_spec.rb"
run_spec "$SPEC_DIR/core/module/method_undefined_spec.rb"
run_spec "$SPEC_DIR/core/module/module_eval_spec.rb"
run_spec "$SPEC_DIR/core/module/module_exec_spec.rb"
run_spec "$SPEC_DIR/core/module/module_function_spec.rb"
run_spec "$SPEC_DIR/core/module/name_spec.rb"
run_spec "$SPEC_DIR/core/module/nesting_spec.rb"
run_spec "$SPEC_DIR/core/module/new_spec.rb"
run_spec "$SPEC_DIR/core/module/prepend_features_spec.rb"
# run_spec "$SPEC_DIR/core/module/prepend_spec.rb"  # 54 of its 55 examples pass; the last needs `1 + 2` to dispatch to a user-defined Integer#+ and `super` from it to reach the native operator
run_spec "$SPEC_DIR/core/module/prepended_spec.rb"
run_spec "$SPEC_DIR/core/module/private_class_method_spec.rb"
run_spec "$SPEC_DIR/core/module/private_constant_spec.rb"
run_spec "$SPEC_DIR/core/module/private_instance_methods_spec.rb"
run_spec "$SPEC_DIR/core/module/private_method_defined_spec.rb"
run_spec "$SPEC_DIR/core/module/private_spec.rb"
run_spec "$SPEC_DIR/core/module/protected_instance_methods_spec.rb"
run_spec "$SPEC_DIR/core/module/protected_method_defined_spec.rb"
run_spec "$SPEC_DIR/core/module/protected_spec.rb"
run_spec "$SPEC_DIR/core/module/public_class_method_spec.rb"
run_spec "$SPEC_DIR/core/module/public_constant_spec.rb"
run_spec "$SPEC_DIR/core/module/public_instance_method_spec.rb"
run_spec "$SPEC_DIR/core/module/public_instance_methods_spec.rb"
run_spec "$SPEC_DIR/core/module/public_method_defined_spec.rb"
run_spec "$SPEC_DIR/core/module/public_spec.rb"
# run_spec "$SPEC_DIR/core/module/refine_spec.rb"  # 21 of its 38 examples pass; the rest need refinement-aware dispatch through send, Symbol#to_proc, interpolation, method objects, respond_to?, and refining a module a class includes
run_spec "$SPEC_DIR/core/module/refinements_spec.rb"
run_spec "$SPEC_DIR/core/module/remove_class_variable_spec.rb"
run_spec "$SPEC_DIR/core/module/remove_const_spec.rb"
run_spec "$SPEC_DIR/core/module/remove_method_spec.rb"
# run_spec "$SPEC_DIR/core/module/ruby2_keywords_spec.rb"  # 6 of its 14 examples pass; the other 8 need a keyword-hash flag on Hash that survives a splat, with Hash.ruby2_keywords_hash and .ruby2_keywords_hash?
run_spec "$SPEC_DIR/core/module/set_temporary_name_spec.rb"
run_spec "$SPEC_DIR/core/module/singleton_class_spec.rb"
run_spec "$SPEC_DIR/core/module/to_s_spec.rb"
run_spec "$SPEC_DIR/core/module/undef_method_spec.rb"
run_spec "$SPEC_DIR/core/module/undefined_instance_methods_spec.rb"
run_spec "$SPEC_DIR/core/module/used_refinements_spec.rb"
run_spec "$SPEC_DIR/core/module/using_spec.rb"
run_spec "$SPEC_DIR/core/kernel/Array_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/Complex_spec.rb"  # 64 of its 66 examples pass; the last two need String to carry an encoding so a UTF-16 argument is refused
run_spec "$SPEC_DIR/core/kernel/Float_spec.rb"
run_spec "$SPEC_DIR/core/kernel/Hash_spec.rb"
run_spec "$SPEC_DIR/core/kernel/Integer_spec.rb"
run_spec "$SPEC_DIR/core/kernel/Rational_spec.rb"
run_spec "$SPEC_DIR/core/kernel/String_spec.rb"
run_spec "$SPEC_DIR/core/kernel/__callee___spec.rb"
run_spec "$SPEC_DIR/core/kernel/__dir___spec.rb"
run_spec "$SPEC_DIR/core/kernel/__method___spec.rb"
run_spec "$SPEC_DIR/core/kernel/abort_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/at_exit_spec.rb"  # 10 of its 12 examples pass; the other two need Ruby's uncaught-exception report format and a lexical __FILE__ inside a block
run_spec "$SPEC_DIR/core/kernel/autoload_relative_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/autoload_spec.rb"  # 19 of its 23 examples pass; the other four need `autoload` inside a module's instance method to register on that module
# run_spec "$SPEC_DIR/core/kernel/backtick_spec.rb"  # 5 of its 8 examples pass; the rest need String to carry an encoding and mspec's stderr-fd capture
run_spec "$SPEC_DIR/core/kernel/binding_spec.rb"
run_spec "$SPEC_DIR/core/kernel/block_given_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/caller_locations_spec.rb"  # 11 of its 12 examples pass; the custom-offset one needs the call stack to hold the same frames MRI does
run_spec "$SPEC_DIR/core/kernel/caller_spec.rb"
run_spec "$SPEC_DIR/core/kernel/case_compare_spec.rb"
run_spec "$SPEC_DIR/core/kernel/catch_spec.rb"
run_spec "$SPEC_DIR/core/kernel/chomp_spec.rb"
run_spec "$SPEC_DIR/core/kernel/chop_spec.rb"
run_spec "$SPEC_DIR/core/kernel/class_spec.rb"
run_spec "$SPEC_DIR/core/kernel/clone_spec.rb"
run_spec "$SPEC_DIR/core/kernel/comparison_spec.rb"
run_spec "$SPEC_DIR/core/kernel/define_singleton_method_spec.rb"
run_spec "$SPEC_DIR/core/kernel/display_spec.rb"
run_spec "$SPEC_DIR/core/kernel/dup_spec.rb"
run_spec "$SPEC_DIR/core/kernel/enum_for_spec.rb"
run_spec "$SPEC_DIR/core/kernel/eql_spec.rb"
run_spec "$SPEC_DIR/core/kernel/equal_value_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/eval_spec.rb"  # 23 of its 56 examples pass; the rest need per-string encodings with magic comments, binding and default-definee semantics, and flip-flop
run_spec "$SPEC_DIR/core/kernel/exec_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/exit_spec.rb"  # 26 of its 30 examples pass; the rest need real Thread semantics and a Fiber class
run_spec "$SPEC_DIR/core/kernel/extend_spec.rb"
run_spec "$SPEC_DIR/core/kernel/fail_spec.rb"
run_spec "$SPEC_DIR/core/kernel/fork_spec.rb"
run_spec "$SPEC_DIR/core/kernel/format_spec.rb"
run_spec "$SPEC_DIR/core/kernel/freeze_spec.rb"
run_spec "$SPEC_DIR/core/kernel/frozen_spec.rb"
run_spec "$SPEC_DIR/core/kernel/gets_spec.rb"
run_spec "$SPEC_DIR/core/kernel/global_variables_spec.rb"
run_spec "$SPEC_DIR/core/kernel/gsub_spec.rb"
run_spec "$SPEC_DIR/core/kernel/initialize_clone_spec.rb"
run_spec "$SPEC_DIR/core/kernel/initialize_copy_spec.rb"
run_spec "$SPEC_DIR/core/kernel/initialize_dup_spec.rb"
run_spec "$SPEC_DIR/core/kernel/inspect_spec.rb"
run_spec "$SPEC_DIR/core/kernel/instance_of_spec.rb"
run_spec "$SPEC_DIR/core/kernel/instance_variable_defined_spec.rb"
run_spec "$SPEC_DIR/core/kernel/instance_variable_get_spec.rb"
run_spec "$SPEC_DIR/core/kernel/instance_variable_set_spec.rb"
run_spec "$SPEC_DIR/core/kernel/instance_variables_spec.rb"
run_spec "$SPEC_DIR/core/kernel/is_a_spec.rb"
run_spec "$SPEC_DIR/core/kernel/itself_spec.rb"
run_spec "$SPEC_DIR/core/kernel/kind_of_spec.rb"
run_spec "$SPEC_DIR/core/kernel/lambda_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/load_spec.rb"  # 97 of its 103 examples pass; the rest need main modelled as its own object and the circular-require warning
run_spec "$SPEC_DIR/core/kernel/local_variables_spec.rb"
run_spec "$SPEC_DIR/core/kernel/loop_spec.rb"
run_spec "$SPEC_DIR/core/kernel/match_spec.rb"
run_spec "$SPEC_DIR/core/kernel/method_spec.rb"
run_spec "$SPEC_DIR/core/kernel/methods_spec.rb"
run_spec "$SPEC_DIR/core/kernel/nil_spec.rb"
run_spec "$SPEC_DIR/core/kernel/not_match_spec.rb"
run_spec "$SPEC_DIR/core/kernel/object_id_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/open_spec.rb"  # 14 of its 15 examples pass; the last needs the open-uri standard library
# run_spec "$SPEC_DIR/core/kernel/p_spec.rb"  # 5 of its 6 examples pass; the last needs STDOUT and STDERR as IO objects for mspec's output_to_fd
run_spec "$SPEC_DIR/core/kernel/pp_spec.rb"
run_spec "$SPEC_DIR/core/kernel/print_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/printf_spec.rb"  # 44 of its 286 examples pass; the rest exercise the shared sprintf suite, whose width, precision, and coercion rules are its own piece of work
run_spec "$SPEC_DIR/core/kernel/private_methods_spec.rb"
run_spec "$SPEC_DIR/core/kernel/proc_spec.rb"
run_spec "$SPEC_DIR/core/kernel/protected_methods_spec.rb"
run_spec "$SPEC_DIR/core/kernel/public_method_spec.rb"
run_spec "$SPEC_DIR/core/kernel/public_methods_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/public_send_spec.rb"  # needs real module ancestry so `super` walks included modules
# run_spec "$SPEC_DIR/core/kernel/putc_spec.rb"  # every example needs a File IO object for `new_io`
# run_spec "$SPEC_DIR/core/kernel/puts_spec.rb"  # every example needs a File IO object for `new_io`
# run_spec "$SPEC_DIR/core/kernel/raise_spec.rb"  # needs Exception#data, three-argument raise with a backtrace, cause chaining, and backtrace preservation on re-raise
# run_spec "$SPEC_DIR/core/kernel/rand_spec.rb"  # needs a Random class, custom range endpoint types, and ruby_exe subprocess support
run_spec "$SPEC_DIR/core/kernel/readline_spec.rb"
run_spec "$SPEC_DIR/core/kernel/readlines_spec.rb"
run_spec "$SPEC_DIR/core/kernel/remove_instance_variable_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/require_relative_spec.rb"  # needs $LOADED_FEATURES tracking, extension resolution, Dir.chdir, and File.symlink
# run_spec "$SPEC_DIR/core/kernel/require_spec.rb"  # hangs, and needs the same $LOADED_FEATURES tracking as require_relative_spec
run_spec "$SPEC_DIR/core/kernel/respond_to_missing_spec.rb"
run_spec "$SPEC_DIR/core/kernel/respond_to_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/select_spec.rb"  # needs IO.pipe and fd-level select
run_spec "$SPEC_DIR/core/kernel/send_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/set_trace_func_spec.rb"  # needs a tracing hook the interpreter calls on each event
# run_spec "$SPEC_DIR/core/kernel/singleton_class_spec.rb"  # needs per-string frozen state for a deduplicated String, and File IO for the reopen example
run_spec "$SPEC_DIR/core/kernel/singleton_method_spec.rb"
run_spec "$SPEC_DIR/core/kernel/singleton_methods_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/sleep_spec.rb"  # hangs: needs Thread scheduling (Thread.pass, wakeup, status) and a Fiber scheduler
# run_spec "$SPEC_DIR/core/kernel/spawn_spec.rb"  # needs subprocess execution and fd-level output capture
# run_spec "$SPEC_DIR/core/kernel/sprintf_spec.rb"  # needs the full format surface: %e %g %G %B, the # flag, width and precision, RangeError, and KeyError for named references
# run_spec "$SPEC_DIR/core/kernel/srand_spec.rb"  # its one remaining example needs ruby_exe subprocess support
run_spec "$SPEC_DIR/core/kernel/sub_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/syscall_spec.rb"  # needs raw OS syscall dispatch
# run_spec "$SPEC_DIR/core/kernel/system_spec.rb"  # needs subprocess execution and Process::Status
run_spec "$SPEC_DIR/core/kernel/taint_spec.rb"
run_spec "$SPEC_DIR/core/kernel/tainted_spec.rb"
run_spec "$SPEC_DIR/core/kernel/tap_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/test_spec.rb"  # needs the file-test operators and File IO
run_spec "$SPEC_DIR/core/kernel/then_spec.rb"
run_spec "$SPEC_DIR/core/kernel/throw_spec.rb"
run_spec "$SPEC_DIR/core/kernel/to_enum_spec.rb"
run_spec "$SPEC_DIR/core/kernel/to_s_spec.rb"
run_spec "$SPEC_DIR/core/kernel/trace_var_spec.rb"
run_spec "$SPEC_DIR/core/kernel/trap_spec.rb"
run_spec "$SPEC_DIR/core/kernel/trust_spec.rb"
run_spec "$SPEC_DIR/core/kernel/untaint_spec.rb"
run_spec "$SPEC_DIR/core/kernel/untrace_var_spec.rb"
run_spec "$SPEC_DIR/core/kernel/untrust_spec.rb"
run_spec "$SPEC_DIR/core/kernel/untrusted_spec.rb"
# run_spec "$SPEC_DIR/core/kernel/warn_spec.rb"  # its last 4 examples shell out through IO.popen
run_spec "$SPEC_DIR/core/kernel/yield_self_spec.rb"
run_spec "$SPEC_DIR/core/basicobject/__id__spec.rb"
run_spec "$SPEC_DIR/core/basicobject/__send___spec.rb"
# run_spec "$SPEC_DIR/core/basicobject/basicobject_spec.rb"  # its method_missing example shells out through IO.popen
run_spec "$SPEC_DIR/core/basicobject/equal_spec.rb"
run_spec "$SPEC_DIR/core/basicobject/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/basicobject/initialize_spec.rb"
# run_spec "$SPEC_DIR/core/basicobject/instance_eval_spec.rb"  # needs a default definee separate from the lexical scope, eval source locations, and block-local scoping
# run_spec "$SPEC_DIR/core/basicobject/instance_exec_spec.rb"  # its last 2 examples need a default definee separate from the lexical scope
run_spec "$SPEC_DIR/core/basicobject/method_missing_spec.rb"
run_spec "$SPEC_DIR/core/basicobject/not_equal_spec.rb"
run_spec "$SPEC_DIR/core/basicobject/not_spec.rb"
run_spec "$SPEC_DIR/core/basicobject/singleton_method_added_spec.rb"
run_spec "$SPEC_DIR/core/basicobject/singleton_method_removed_spec.rb"
run_spec "$SPEC_DIR/core/basicobject/singleton_method_undefined_spec.rb"

# 4.10 - 4.13: Exceptions and Signals
run_spec "$SPEC_DIR/core/exception/backtrace_locations_spec.rb"
run_spec "$SPEC_DIR/core/exception/backtrace_spec.rb"
run_spec "$SPEC_DIR/core/exception/case_compare_spec.rb"
run_spec "$SPEC_DIR/core/exception/cause_spec.rb"
run_spec "$SPEC_DIR/core/exception/detailed_message_spec.rb"
run_spec "$SPEC_DIR/core/exception/dup_spec.rb"
run_spec "$SPEC_DIR/core/exception/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/exception/errno_spec.rb"
run_spec "$SPEC_DIR/core/exception/exception_spec.rb"
run_spec "$SPEC_DIR/core/exception/exit_value_spec.rb"
run_spec "$SPEC_DIR/core/exception/frozen_error_spec.rb"
# run_spec "$SPEC_DIR/core/exception/full_message_spec.rb"  # needs the caller when an exception has no backtrace, and file attribution for a raise inside a block
run_spec "$SPEC_DIR/core/exception/hierarchy_spec.rb"
run_spec "$SPEC_DIR/core/exception/inspect_spec.rb"
# run_spec "$SPEC_DIR/core/exception/interrupt_spec.rb"  # 3 of its 5 examples pass; the other 2 need ruby_exe and IO.popen subprocess support
run_spec "$SPEC_DIR/core/exception/io_error_spec.rb"
run_spec "$SPEC_DIR/core/exception/key_error_spec.rb"
run_spec "$SPEC_DIR/core/exception/load_error_spec.rb"
run_spec "$SPEC_DIR/core/exception/message_spec.rb"
run_spec "$SPEC_DIR/core/exception/name_error_spec.rb"
run_spec "$SPEC_DIR/core/exception/name_spec.rb"
run_spec "$SPEC_DIR/core/exception/new_spec.rb"
run_spec "$SPEC_DIR/core/exception/no_method_error_spec.rb"
run_spec "$SPEC_DIR/core/exception/reason_spec.rb"
run_spec "$SPEC_DIR/core/exception/receiver_spec.rb"
run_spec "$SPEC_DIR/core/exception/result_spec.rb"
run_spec "$SPEC_DIR/core/exception/set_backtrace_spec.rb"
# run_spec "$SPEC_DIR/core/exception/signal_exception_spec.rb"  # 12 of its 16 examples pass; the other 4 need ruby_exe and IO.popen subprocess support
run_spec "$SPEC_DIR/core/exception/signm_spec.rb"
run_spec "$SPEC_DIR/core/exception/signo_spec.rb"
run_spec "$SPEC_DIR/core/exception/standard_error_spec.rb"
run_spec "$SPEC_DIR/core/exception/status_spec.rb"
run_spec "$SPEC_DIR/core/exception/success_spec.rb"
run_spec "$SPEC_DIR/core/exception/syntax_error_spec.rb"
run_spec "$SPEC_DIR/core/exception/system_call_error_spec.rb"
run_spec "$SPEC_DIR/core/exception/system_exit_spec.rb"
run_spec "$SPEC_DIR/core/exception/to_s_spec.rb"
# run_spec "$SPEC_DIR/core/exception/top_level_spec.rb"  # its last two examples hang the runner, needing real Thread and Fiber with a bare `sleep` and `Thread#stop?`
run_spec "$SPEC_DIR/core/exception/uncaught_throw_error_spec.rb"
run_spec "$SPEC_DIR/core/systemexit"
run_spec "$SPEC_DIR/core/signal/list_spec.rb"
run_spec "$SPEC_DIR/core/signal/signame_spec.rb"
# run_spec "$SPEC_DIR/core/signal/trap_spec.rb"  # needs Thread#group with Thread.main.group, and IO.pipe with a write to a closed pipe dying by SIGPIPE
run_spec "$SPEC_DIR/core/warning/categories_spec.rb"
run_spec "$SPEC_DIR/core/warning/element_reference_spec.rb"
run_spec "$SPEC_DIR/core/warning/element_set_spec.rb"
run_spec "$SPEC_DIR/core/warning/warn_spec.rb"
# run_spec "$SPEC_DIR/core/warning/performance_warning_spec.rb"  # needs `1 + 2` to dispatch to a user-defined Integer#+, the same gap module/prepend_spec waits on

# 4.14 - 4.19: Numeric Types
run_spec "$SPEC_DIR/core/integer/abs_spec.rb"
run_spec "$SPEC_DIR/core/integer/allbits_spec.rb"
run_spec "$SPEC_DIR/core/integer/anybits_spec.rb"
run_spec "$SPEC_DIR/core/integer/bit_and_spec.rb"
run_spec "$SPEC_DIR/core/integer/bit_or_spec.rb"
run_spec "$SPEC_DIR/core/integer/bit_xor_spec.rb"
run_spec "$SPEC_DIR/core/integer/case_compare_spec.rb"
run_spec "$SPEC_DIR/core/integer/ceil_spec.rb"
run_spec "$SPEC_DIR/core/integer/ceildiv_spec.rb"
run_spec "$SPEC_DIR/core/integer/coerce_spec.rb"
run_spec "$SPEC_DIR/core/integer/comparison_spec.rb"
run_spec "$SPEC_DIR/core/integer/complement_spec.rb"
run_spec "$SPEC_DIR/core/integer/constants_spec.rb"
run_spec "$SPEC_DIR/core/integer/denominator_spec.rb"
run_spec "$SPEC_DIR/core/integer/digits_spec.rb"
run_spec "$SPEC_DIR/core/integer/divide_spec.rb"
run_spec "$SPEC_DIR/core/integer/divmod_spec.rb"
run_spec "$SPEC_DIR/core/integer/dup_spec.rb"
run_spec "$SPEC_DIR/core/integer/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/integer/even_spec.rb"
run_spec "$SPEC_DIR/core/integer/fdiv_spec.rb"
run_spec "$SPEC_DIR/core/integer/floor_spec.rb"
run_spec "$SPEC_DIR/core/integer/gcd_spec.rb"
run_spec "$SPEC_DIR/core/integer/gcdlcm_spec.rb"
run_spec "$SPEC_DIR/core/integer/gt_spec.rb"
run_spec "$SPEC_DIR/core/integer/gte_spec.rb"
run_spec "$SPEC_DIR/core/integer/integer_spec.rb"
run_spec "$SPEC_DIR/core/integer/lcm_spec.rb"
run_spec "$SPEC_DIR/core/integer/lt_spec.rb"
run_spec "$SPEC_DIR/core/integer/lte_spec.rb"
run_spec "$SPEC_DIR/core/integer/magnitude_spec.rb"
run_spec "$SPEC_DIR/core/integer/minus_spec.rb"
run_spec "$SPEC_DIR/core/integer/modulo_spec.rb"
run_spec "$SPEC_DIR/core/integer/multiply_spec.rb"
run_spec "$SPEC_DIR/core/integer/nobits_spec.rb"
run_spec "$SPEC_DIR/core/integer/numerator_spec.rb"
run_spec "$SPEC_DIR/core/integer/odd_spec.rb"
run_spec "$SPEC_DIR/core/integer/ord_spec.rb"
run_spec "$SPEC_DIR/core/integer/rationalize_spec.rb"
run_spec "$SPEC_DIR/core/integer/remainder_spec.rb"
run_spec "$SPEC_DIR/core/integer/round_spec.rb"
run_spec "$SPEC_DIR/core/integer/size_spec.rb"
run_spec "$SPEC_DIR/core/integer/sqrt_spec.rb"
run_spec "$SPEC_DIR/core/integer/to_f_spec.rb"
run_spec "$SPEC_DIR/core/integer/to_i_spec.rb"
run_spec "$SPEC_DIR/core/integer/to_int_spec.rb"
run_spec "$SPEC_DIR/core/integer/to_r_spec.rb"
run_spec "$SPEC_DIR/core/integer/truncate_spec.rb"
run_spec "$SPEC_DIR/core/integer/try_convert_spec.rb"
run_spec "$SPEC_DIR/core/integer/zero_spec.rb"
# run_spec "$SPEC_DIR/core/integer"  # the other 16 files are enabled one at a time as they pass; exponent_spec and pow_spec also need `1 ** 4611686018427387904` to answer without computing it
run_spec "$SPEC_DIR/core/float/abs_spec.rb"
run_spec "$SPEC_DIR/core/float/angle_spec.rb"
run_spec "$SPEC_DIR/core/float/arg_spec.rb"
run_spec "$SPEC_DIR/core/float/case_compare_spec.rb"
run_spec "$SPEC_DIR/core/float/ceil_spec.rb"
run_spec "$SPEC_DIR/core/float/coerce_spec.rb"
run_spec "$SPEC_DIR/core/float/denominator_spec.rb"
run_spec "$SPEC_DIR/core/float/divide_spec.rb"
run_spec "$SPEC_DIR/core/float/divmod_spec.rb"
run_spec "$SPEC_DIR/core/float/dup_spec.rb"
run_spec "$SPEC_DIR/core/float/eql_spec.rb"
run_spec "$SPEC_DIR/core/float/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/float/fdiv_spec.rb"
run_spec "$SPEC_DIR/core/float/finite_spec.rb"
run_spec "$SPEC_DIR/core/float/float_spec.rb"
run_spec "$SPEC_DIR/core/float/floor_spec.rb"
run_spec "$SPEC_DIR/core/float/gt_spec.rb"
run_spec "$SPEC_DIR/core/float/gte_spec.rb"
run_spec "$SPEC_DIR/core/float/hash_spec.rb"
run_spec "$SPEC_DIR/core/float/infinite_spec.rb"
run_spec "$SPEC_DIR/core/float/lt_spec.rb"
run_spec "$SPEC_DIR/core/float/lte_spec.rb"
run_spec "$SPEC_DIR/core/float/magnitude_spec.rb"
run_spec "$SPEC_DIR/core/float/minus_spec.rb"
run_spec "$SPEC_DIR/core/float/modulo_spec.rb"
run_spec "$SPEC_DIR/core/float/multiply_spec.rb"
run_spec "$SPEC_DIR/core/float/nan_spec.rb"
run_spec "$SPEC_DIR/core/float/negative_spec.rb"
run_spec "$SPEC_DIR/core/float/next_float_spec.rb"
run_spec "$SPEC_DIR/core/float/numerator_spec.rb"
run_spec "$SPEC_DIR/core/float/phase_spec.rb"
run_spec "$SPEC_DIR/core/float/plus_spec.rb"
run_spec "$SPEC_DIR/core/float/positive_spec.rb"
run_spec "$SPEC_DIR/core/float/prev_float_spec.rb"
run_spec "$SPEC_DIR/core/float/quo_spec.rb"
run_spec "$SPEC_DIR/core/float/to_f_spec.rb"
run_spec "$SPEC_DIR/core/float/to_i_spec.rb"
run_spec "$SPEC_DIR/core/float/to_int_spec.rb"
run_spec "$SPEC_DIR/core/float/to_r_spec.rb"
run_spec "$SPEC_DIR/core/float/truncate_spec.rb"
run_spec "$SPEC_DIR/core/float/uminus_spec.rb"
run_spec "$SPEC_DIR/core/float/uplus_spec.rb"
run_spec "$SPEC_DIR/core/float/zero_spec.rb"
# run_spec "$SPEC_DIR/core/float"  # the other 7 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/numeric/abs_spec.rb"
run_spec "$SPEC_DIR/core/numeric/ceil_spec.rb"
run_spec "$SPEC_DIR/core/numeric/clone_spec.rb"
run_spec "$SPEC_DIR/core/numeric/coerce_spec.rb"
run_spec "$SPEC_DIR/core/numeric/comparison_spec.rb"
run_spec "$SPEC_DIR/core/numeric/conj_spec.rb"
run_spec "$SPEC_DIR/core/numeric/conjugate_spec.rb"
run_spec "$SPEC_DIR/core/numeric/denominator_spec.rb"
run_spec "$SPEC_DIR/core/numeric/div_spec.rb"
run_spec "$SPEC_DIR/core/numeric/divmod_spec.rb"
run_spec "$SPEC_DIR/core/numeric/dup_spec.rb"
run_spec "$SPEC_DIR/core/numeric/eql_spec.rb"
run_spec "$SPEC_DIR/core/numeric/fdiv_spec.rb"
run_spec "$SPEC_DIR/core/numeric/finite_spec.rb"
run_spec "$SPEC_DIR/core/numeric/floor_spec.rb"
run_spec "$SPEC_DIR/core/numeric/imag_spec.rb"
run_spec "$SPEC_DIR/core/numeric/imaginary_spec.rb"
run_spec "$SPEC_DIR/core/numeric/infinite_spec.rb"
run_spec "$SPEC_DIR/core/numeric/integer_spec.rb"
run_spec "$SPEC_DIR/core/numeric/magnitude_spec.rb"
run_spec "$SPEC_DIR/core/numeric/modulo_spec.rb"
run_spec "$SPEC_DIR/core/numeric/negative_spec.rb"
run_spec "$SPEC_DIR/core/numeric/nonzero_spec.rb"
run_spec "$SPEC_DIR/core/numeric/numerator_spec.rb"
run_spec "$SPEC_DIR/core/numeric/numeric_spec.rb"
run_spec "$SPEC_DIR/core/numeric/positive_spec.rb"
run_spec "$SPEC_DIR/core/numeric/real_spec.rb"
run_spec "$SPEC_DIR/core/numeric/round_spec.rb"
run_spec "$SPEC_DIR/core/numeric/to_int_spec.rb"
run_spec "$SPEC_DIR/core/numeric/truncate_spec.rb"
run_spec "$SPEC_DIR/core/numeric/uplus_spec.rb"
run_spec "$SPEC_DIR/core/numeric/zero_spec.rb"
# run_spec "$SPEC_DIR/core/numeric"  # the other 14 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/complex/abs2_spec.rb"
run_spec "$SPEC_DIR/core/complex/abs_spec.rb"
run_spec "$SPEC_DIR/core/complex/angle_spec.rb"
run_spec "$SPEC_DIR/core/complex/arg_spec.rb"
run_spec "$SPEC_DIR/core/complex/comparison_spec.rb"
run_spec "$SPEC_DIR/core/complex/conj_spec.rb"
run_spec "$SPEC_DIR/core/complex/conjugate_spec.rb"
run_spec "$SPEC_DIR/core/complex/constants_spec.rb"
run_spec "$SPEC_DIR/core/complex/denominator_spec.rb"
run_spec "$SPEC_DIR/core/complex/eql_spec.rb"
run_spec "$SPEC_DIR/core/complex/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/complex/finite_spec.rb"
run_spec "$SPEC_DIR/core/complex/hash_spec.rb"
run_spec "$SPEC_DIR/core/complex/imag_spec.rb"
run_spec "$SPEC_DIR/core/complex/imaginary_spec.rb"
run_spec "$SPEC_DIR/core/complex/infinite_spec.rb"
run_spec "$SPEC_DIR/core/complex/inspect_spec.rb"
run_spec "$SPEC_DIR/core/complex/integer_spec.rb"
run_spec "$SPEC_DIR/core/complex/magnitude_spec.rb"
run_spec "$SPEC_DIR/core/complex/negative_spec.rb"
run_spec "$SPEC_DIR/core/complex/numerator_spec.rb"
run_spec "$SPEC_DIR/core/complex/phase_spec.rb"
run_spec "$SPEC_DIR/core/complex/polar_spec.rb"
run_spec "$SPEC_DIR/core/complex/positive_spec.rb"
run_spec "$SPEC_DIR/core/complex/rationalize_spec.rb"
run_spec "$SPEC_DIR/core/complex/real_spec.rb"
run_spec "$SPEC_DIR/core/complex/rect_spec.rb"
run_spec "$SPEC_DIR/core/complex/rectangular_spec.rb"
run_spec "$SPEC_DIR/core/complex/to_c_spec.rb"
run_spec "$SPEC_DIR/core/complex/to_f_spec.rb"
run_spec "$SPEC_DIR/core/complex/to_i_spec.rb"
run_spec "$SPEC_DIR/core/complex/to_r_spec.rb"
run_spec "$SPEC_DIR/core/complex/to_s_spec.rb"
run_spec "$SPEC_DIR/core/complex/uminus_spec.rb"
# run_spec "$SPEC_DIR/core/complex"  # the other 9 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/rational/abs_spec.rb"
run_spec "$SPEC_DIR/core/rational/ceil_spec.rb"
run_spec "$SPEC_DIR/core/rational/comparison_spec.rb"
run_spec "$SPEC_DIR/core/rational/denominator_spec.rb"
run_spec "$SPEC_DIR/core/rational/div_spec.rb"
run_spec "$SPEC_DIR/core/rational/divide_spec.rb"
run_spec "$SPEC_DIR/core/rational/divmod_spec.rb"
run_spec "$SPEC_DIR/core/rational/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/rational/fdiv_spec.rb"
run_spec "$SPEC_DIR/core/rational/floor_spec.rb"
run_spec "$SPEC_DIR/core/rational/hash_spec.rb"
run_spec "$SPEC_DIR/core/rational/inspect_spec.rb"
run_spec "$SPEC_DIR/core/rational/integer_spec.rb"
run_spec "$SPEC_DIR/core/rational/magnitude_spec.rb"
run_spec "$SPEC_DIR/core/rational/minus_spec.rb"
run_spec "$SPEC_DIR/core/rational/modulo_spec.rb"
run_spec "$SPEC_DIR/core/rational/multiply_spec.rb"
run_spec "$SPEC_DIR/core/rational/numerator_spec.rb"
run_spec "$SPEC_DIR/core/rational/plus_spec.rb"
run_spec "$SPEC_DIR/core/rational/rational_spec.rb"
run_spec "$SPEC_DIR/core/rational/remainder_spec.rb"
run_spec "$SPEC_DIR/core/rational/round_spec.rb"
run_spec "$SPEC_DIR/core/rational/to_f_spec.rb"
run_spec "$SPEC_DIR/core/rational/to_i_spec.rb"
run_spec "$SPEC_DIR/core/rational/to_s_spec.rb"
run_spec "$SPEC_DIR/core/rational/truncate_spec.rb"
run_spec "$SPEC_DIR/core/rational/zero_spec.rb"
# run_spec "$SPEC_DIR/core/rational"  # the other 5 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/math/acos_spec.rb"
run_spec "$SPEC_DIR/core/math/acosh_spec.rb"
run_spec "$SPEC_DIR/core/math/asin_spec.rb"
run_spec "$SPEC_DIR/core/math/asinh_spec.rb"
run_spec "$SPEC_DIR/core/math/atan2_spec.rb"
run_spec "$SPEC_DIR/core/math/atan_spec.rb"
run_spec "$SPEC_DIR/core/math/atanh_spec.rb"
run_spec "$SPEC_DIR/core/math/cbrt_spec.rb"
run_spec "$SPEC_DIR/core/math/constants_spec.rb"
run_spec "$SPEC_DIR/core/math/cos_spec.rb"
run_spec "$SPEC_DIR/core/math/cosh_spec.rb"
run_spec "$SPEC_DIR/core/math/erf_spec.rb"
run_spec "$SPEC_DIR/core/math/erfc_spec.rb"
run_spec "$SPEC_DIR/core/math/exp_spec.rb"
run_spec "$SPEC_DIR/core/math/expm1_spec.rb"
run_spec "$SPEC_DIR/core/math/frexp_spec.rb"
run_spec "$SPEC_DIR/core/math/hypot_spec.rb"
run_spec "$SPEC_DIR/core/math/ldexp_spec.rb"
run_spec "$SPEC_DIR/core/math/log10_spec.rb"
run_spec "$SPEC_DIR/core/math/log1p_spec.rb"
run_spec "$SPEC_DIR/core/math/log2_spec.rb"
run_spec "$SPEC_DIR/core/math/log_spec.rb"
run_spec "$SPEC_DIR/core/math/sin_spec.rb"
run_spec "$SPEC_DIR/core/math/sinh_spec.rb"
run_spec "$SPEC_DIR/core/math/sqrt_spec.rb"
run_spec "$SPEC_DIR/core/math/tan_spec.rb"
run_spec "$SPEC_DIR/core/math/tanh_spec.rb"
# run_spec "$SPEC_DIR/core/math"  # gamma_spec and lgamma_spec need a gamma function accurate to the last digit

# 4.20 - 4.25: Collections
run_spec "$SPEC_DIR/core/array/allocate_spec.rb"
run_spec "$SPEC_DIR/core/array/append_spec.rb"
run_spec "$SPEC_DIR/core/array/array_spec.rb"
run_spec "$SPEC_DIR/core/array/assoc_spec.rb"
run_spec "$SPEC_DIR/core/array/at_spec.rb"
run_spec "$SPEC_DIR/core/array/clear_spec.rb"
run_spec "$SPEC_DIR/core/array/collect_spec.rb"
run_spec "$SPEC_DIR/core/array/compact_spec.rb"
run_spec "$SPEC_DIR/core/array/comparison_spec.rb"
run_spec "$SPEC_DIR/core/array/concat_spec.rb"
run_spec "$SPEC_DIR/core/array/constructor_spec.rb"
run_spec "$SPEC_DIR/core/array/count_spec.rb"
run_spec "$SPEC_DIR/core/array/deconstruct_spec.rb"
run_spec "$SPEC_DIR/core/array/delete_at_spec.rb"
run_spec "$SPEC_DIR/core/array/delete_if_spec.rb"
run_spec "$SPEC_DIR/core/array/delete_spec.rb"
run_spec "$SPEC_DIR/core/array/difference_spec.rb"
run_spec "$SPEC_DIR/core/array/drop_spec.rb"
run_spec "$SPEC_DIR/core/array/drop_while_spec.rb"
run_spec "$SPEC_DIR/core/array/each_index_spec.rb"
run_spec "$SPEC_DIR/core/array/each_spec.rb"
run_spec "$SPEC_DIR/core/array/element_set_spec.rb"
run_spec "$SPEC_DIR/core/array/empty_spec.rb"
run_spec "$SPEC_DIR/core/array/eql_spec.rb"
run_spec "$SPEC_DIR/core/array/fetch_spec.rb"
run_spec "$SPEC_DIR/core/array/fetch_values_spec.rb"
run_spec "$SPEC_DIR/core/array/filter_spec.rb"
run_spec "$SPEC_DIR/core/array/find_index_spec.rb"
run_spec "$SPEC_DIR/core/array/first_spec.rb"
run_spec "$SPEC_DIR/core/array/frozen_spec.rb"
run_spec "$SPEC_DIR/core/array/include_spec.rb"
run_spec "$SPEC_DIR/core/array/index_spec.rb"
run_spec "$SPEC_DIR/core/array/insert_spec.rb"
run_spec "$SPEC_DIR/core/array/intersect_spec.rb"
run_spec "$SPEC_DIR/core/array/intersection_spec.rb"
run_spec "$SPEC_DIR/core/array/keep_if_spec.rb"
run_spec "$SPEC_DIR/core/array/last_spec.rb"
run_spec "$SPEC_DIR/core/array/length_spec.rb"
run_spec "$SPEC_DIR/core/array/map_spec.rb"
run_spec "$SPEC_DIR/core/array/max_spec.rb"
run_spec "$SPEC_DIR/core/array/min_spec.rb"
run_spec "$SPEC_DIR/core/array/minmax_spec.rb"
run_spec "$SPEC_DIR/core/array/minus_spec.rb"
run_spec "$SPEC_DIR/core/array/partition_spec.rb"
run_spec "$SPEC_DIR/core/array/plus_spec.rb"
run_spec "$SPEC_DIR/core/array/pop_spec.rb"
run_spec "$SPEC_DIR/core/array/prepend_spec.rb"
run_spec "$SPEC_DIR/core/array/push_spec.rb"
run_spec "$SPEC_DIR/core/array/rassoc_spec.rb"
run_spec "$SPEC_DIR/core/array/replace_spec.rb"
run_spec "$SPEC_DIR/core/array/reverse_each_spec.rb"
run_spec "$SPEC_DIR/core/array/reverse_spec.rb"
run_spec "$SPEC_DIR/core/array/rotate_spec.rb"
run_spec "$SPEC_DIR/core/array/select_spec.rb"
run_spec "$SPEC_DIR/core/array/shift_spec.rb"
run_spec "$SPEC_DIR/core/array/size_spec.rb"
run_spec "$SPEC_DIR/core/array/sort_by_spec.rb"
run_spec "$SPEC_DIR/core/array/sum_spec.rb"
run_spec "$SPEC_DIR/core/array/take_spec.rb"
run_spec "$SPEC_DIR/core/array/take_while_spec.rb"
run_spec "$SPEC_DIR/core/array/to_a_spec.rb"
run_spec "$SPEC_DIR/core/array/to_ary_spec.rb"
run_spec "$SPEC_DIR/core/array/transpose_spec.rb"
run_spec "$SPEC_DIR/core/array/union_spec.rb"
run_spec "$SPEC_DIR/core/array/unshift_spec.rb"
run_spec "$SPEC_DIR/core/array/values_at_spec.rb"
run_spec "$SPEC_DIR/core/array/bsearch_spec.rb"
run_spec "$SPEC_DIR/core/array/bsearch_index_spec.rb"
run_spec "$SPEC_DIR/core/array/combination_spec.rb"
run_spec "$SPEC_DIR/core/array/permutation_spec.rb"
run_spec "$SPEC_DIR/core/array/product_spec.rb"
run_spec "$SPEC_DIR/core/array/repeated_combination_spec.rb"
run_spec "$SPEC_DIR/core/array/repeated_permutation_spec.rb"
run_spec "$SPEC_DIR/core/array/rindex_spec.rb"
# run_spec "$SPEC_DIR/core/array"  # the other 28 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/hash/allocate_spec.rb"
run_spec "$SPEC_DIR/core/hash/any_spec.rb"
run_spec "$SPEC_DIR/core/hash/clear_spec.rb"
run_spec "$SPEC_DIR/core/hash/clone_spec.rb"
run_spec "$SPEC_DIR/core/hash/compact_spec.rb"
run_spec "$SPEC_DIR/core/hash/deconstruct_keys_spec.rb"
run_spec "$SPEC_DIR/core/hash/default_spec.rb"
run_spec "$SPEC_DIR/core/hash/delete_if_spec.rb"
run_spec "$SPEC_DIR/core/hash/delete_spec.rb"
run_spec "$SPEC_DIR/core/hash/each_key_spec.rb"
run_spec "$SPEC_DIR/core/hash/each_value_spec.rb"
run_spec "$SPEC_DIR/core/hash/empty_spec.rb"
run_spec "$SPEC_DIR/core/hash/except_spec.rb"
run_spec "$SPEC_DIR/core/hash/fetch_spec.rb"
run_spec "$SPEC_DIR/core/hash/fetch_values_spec.rb"
run_spec "$SPEC_DIR/core/hash/filter_spec.rb"
run_spec "$SPEC_DIR/core/hash/flatten_spec.rb"
run_spec "$SPEC_DIR/core/hash/gt_spec.rb"
run_spec "$SPEC_DIR/core/hash/gte_spec.rb"
run_spec "$SPEC_DIR/core/hash/has_key_spec.rb"
run_spec "$SPEC_DIR/core/hash/has_value_spec.rb"
run_spec "$SPEC_DIR/core/hash/include_spec.rb"
run_spec "$SPEC_DIR/core/hash/invert_spec.rb"
run_spec "$SPEC_DIR/core/hash/keep_if_spec.rb"
run_spec "$SPEC_DIR/core/hash/key_spec.rb"
run_spec "$SPEC_DIR/core/hash/keys_spec.rb"
run_spec "$SPEC_DIR/core/hash/length_spec.rb"
run_spec "$SPEC_DIR/core/hash/lt_spec.rb"
run_spec "$SPEC_DIR/core/hash/lte_spec.rb"
run_spec "$SPEC_DIR/core/hash/member_spec.rb"
run_spec "$SPEC_DIR/core/hash/new_spec.rb"
run_spec "$SPEC_DIR/core/hash/rassoc_spec.rb"
run_spec "$SPEC_DIR/core/hash/reject_spec.rb"
run_spec "$SPEC_DIR/core/hash/replace_spec.rb"
run_spec "$SPEC_DIR/core/hash/select_spec.rb"
run_spec "$SPEC_DIR/core/hash/shift_spec.rb"
run_spec "$SPEC_DIR/core/hash/size_spec.rb"
run_spec "$SPEC_DIR/core/hash/slice_spec.rb"
run_spec "$SPEC_DIR/core/hash/sort_spec.rb"
run_spec "$SPEC_DIR/core/hash/to_a_spec.rb"
run_spec "$SPEC_DIR/core/hash/to_h_spec.rb"
run_spec "$SPEC_DIR/core/hash/to_hash_spec.rb"
run_spec "$SPEC_DIR/core/hash/transform_values_spec.rb"
run_spec "$SPEC_DIR/core/hash/update_spec.rb"
run_spec "$SPEC_DIR/core/hash/value_spec.rb"
run_spec "$SPEC_DIR/core/hash/values_at_spec.rb"
run_spec "$SPEC_DIR/core/hash/values_spec.rb"
run_spec "$SPEC_DIR/core/hash/to_proc_spec.rb"
# run_spec "$SPEC_DIR/core/hash"  # the other 21 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/set/add_spec.rb"
run_spec "$SPEC_DIR/core/set/append_spec.rb"
run_spec "$SPEC_DIR/core/set/case_compare_spec.rb"
run_spec "$SPEC_DIR/core/set/case_equality_spec.rb"
run_spec "$SPEC_DIR/core/set/clear_spec.rb"
run_spec "$SPEC_DIR/core/set/collect_spec.rb"
run_spec "$SPEC_DIR/core/set/comparison_spec.rb"
run_spec "$SPEC_DIR/core/set/constructor_spec.rb"
run_spec "$SPEC_DIR/core/set/delete_if_spec.rb"
run_spec "$SPEC_DIR/core/set/delete_spec.rb"
run_spec "$SPEC_DIR/core/set/difference_spec.rb"
run_spec "$SPEC_DIR/core/set/disjoint_spec.rb"
run_spec "$SPEC_DIR/core/set/each_spec.rb"
run_spec "$SPEC_DIR/core/set/empty_spec.rb"
run_spec "$SPEC_DIR/core/set/eql_spec.rb"
run_spec "$SPEC_DIR/core/set/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/set/exclusion_spec.rb"
run_spec "$SPEC_DIR/core/set/filter_spec.rb"
run_spec "$SPEC_DIR/core/set/flatten_merge_spec.rb"
run_spec "$SPEC_DIR/core/set/hash_spec.rb"
run_spec "$SPEC_DIR/core/set/include_spec.rb"
run_spec "$SPEC_DIR/core/set/initialize_clone_spec.rb"
run_spec "$SPEC_DIR/core/set/inspect_spec.rb"
run_spec "$SPEC_DIR/core/set/intersect_spec.rb"
run_spec "$SPEC_DIR/core/set/intersection_spec.rb"
run_spec "$SPEC_DIR/core/set/join_spec.rb"
run_spec "$SPEC_DIR/core/set/keep_if_spec.rb"
run_spec "$SPEC_DIR/core/set/length_spec.rb"
run_spec "$SPEC_DIR/core/set/map_spec.rb"
run_spec "$SPEC_DIR/core/set/member_spec.rb"
run_spec "$SPEC_DIR/core/set/merge_spec.rb"
run_spec "$SPEC_DIR/core/set/minus_spec.rb"
run_spec "$SPEC_DIR/core/set/plus_spec.rb"
run_spec "$SPEC_DIR/core/set/proper_subset_spec.rb"
run_spec "$SPEC_DIR/core/set/proper_superset_spec.rb"
run_spec "$SPEC_DIR/core/set/reject_spec.rb"
run_spec "$SPEC_DIR/core/set/replace_spec.rb"
run_spec "$SPEC_DIR/core/set/select_spec.rb"
run_spec "$SPEC_DIR/core/set/set_spec.rb"
run_spec "$SPEC_DIR/core/set/size_spec.rb"
run_spec "$SPEC_DIR/core/set/subset_spec.rb"
run_spec "$SPEC_DIR/core/set/subtract_spec.rb"
run_spec "$SPEC_DIR/core/set/superset_spec.rb"
run_spec "$SPEC_DIR/core/set/to_a_spec.rb"
run_spec "$SPEC_DIR/core/set/to_s_spec.rb"
run_spec "$SPEC_DIR/core/set/union_spec.rb"
run_spec "$SPEC_DIR/core/set/classify_spec.rb"
run_spec "$SPEC_DIR/core/set/divide_spec.rb"
run_spec "$SPEC_DIR/core/set/flatten_spec.rb"
# run_spec "$SPEC_DIR/core/set"  # the other 3 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/range/begin_spec.rb"
run_spec "$SPEC_DIR/core/range/count_spec.rb"
run_spec "$SPEC_DIR/core/range/end_spec.rb"
run_spec "$SPEC_DIR/core/range/eql_spec.rb"
run_spec "$SPEC_DIR/core/range/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/range/exclude_end_spec.rb"
run_spec "$SPEC_DIR/core/range/first_spec.rb"
run_spec "$SPEC_DIR/core/range/frozen_spec.rb"
run_spec "$SPEC_DIR/core/range/hash_spec.rb"
run_spec "$SPEC_DIR/core/range/inspect_spec.rb"
run_spec "$SPEC_DIR/core/range/last_spec.rb"
run_spec "$SPEC_DIR/core/range/range_spec.rb"
run_spec "$SPEC_DIR/core/range/size_spec.rb"
run_spec "$SPEC_DIR/core/range/to_a_spec.rb"
run_spec "$SPEC_DIR/core/range/to_s_spec.rb"
run_spec "$SPEC_DIR/core/range/to_set_spec.rb"
# run_spec "$SPEC_DIR/core/range"  # the other 17 files are enabled one at a time as they pass

run_spec "$SPEC_DIR/core/method/call_spec.rb"
run_spec "$SPEC_DIR/core/method/case_compare_spec.rb"
run_spec "$SPEC_DIR/core/method/element_reference_spec.rb"
run_spec "$SPEC_DIR/core/method/name_spec.rb"
run_spec "$SPEC_DIR/core/method/original_name_spec.rb"
run_spec "$SPEC_DIR/core/method/private_spec.rb"
run_spec "$SPEC_DIR/core/method/protected_spec.rb"
run_spec "$SPEC_DIR/core/method/public_spec.rb"
run_spec "$SPEC_DIR/core/method/receiver_spec.rb"
run_spec "$SPEC_DIR/core/method/arity_spec.rb"
run_spec "$SPEC_DIR/core/method/super_method_spec.rb"
run_spec "$SPEC_DIR/core/method/unbind_spec.rb"
# run_spec "$SPEC_DIR/core/method"  # the other 13 files are enabled one at a time as they pass

run_spec "$SPEC_DIR/core/proc/allocate_spec.rb"
run_spec "$SPEC_DIR/core/proc/binding_spec.rb"
run_spec "$SPEC_DIR/core/proc/block_pass_spec.rb"
run_spec "$SPEC_DIR/core/proc/eql_spec.rb"
run_spec "$SPEC_DIR/core/proc/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/proc/hash_spec.rb"
run_spec "$SPEC_DIR/core/proc/to_proc_spec.rb"
# run_spec "$SPEC_DIR/core/proc"  # the other 16 files are enabled one at a time as they pass

run_spec "$SPEC_DIR/core/enumerator/each_with_object_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/enumerator_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/first_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/next_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/next_values_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/peek_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/peek_values_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/plus_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/with_object_spec.rb"
# run_spec "$SPEC_DIR/core/enumerator"  # the other 13 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/enumerator/chain/each_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/chain/inspect_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/chain/size_spec.rb"
# run_spec "$SPEC_DIR/core/enumerator/chain"  # the other 2 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/enumerator/lazy/chunk_while_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/collect_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/compact_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/drop_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/drop_while_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/eager_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/filter_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/filter_map_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/find_all_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/force_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/lazy_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/map_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/reject_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/slice_after_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/slice_before_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/slice_when_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/take_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/take_while_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/uniq_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/with_index_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/chunk_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/collect_concat_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/grep_v_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/initialize_spec.rb"
run_spec "$SPEC_DIR/core/enumerator/lazy/select_spec.rb"
# run_spec "$SPEC_DIR/core/enumerator/lazy"  # the other 6 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/enumerable/all_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/any_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/collect_concat_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/compact_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/count_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/detect_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/drop_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/drop_while_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/each_cons_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/each_entry_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/each_slice_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/each_with_index_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/each_with_object_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/entries_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/filter_map_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/filter_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/find_all_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/find_index_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/find_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/first_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/flat_map_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/grep_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/grep_v_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/group_by_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/include_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/inject_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/max_by_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/max_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/member_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/min_by_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/min_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/minmax_by_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/minmax_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/none_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/one_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/partition_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/reduce_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/reject_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/reverse_each_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/select_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/sort_by_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/sort_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/sum_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/take_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/take_while_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/tally_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/to_a_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/to_set_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/chain_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/lazy_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/zip_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/chunk_while_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/slice_after_spec.rb"
run_spec "$SPEC_DIR/core/enumerable/slice_when_spec.rb"
# run_spec "$SPEC_DIR/core/enumerable"  # the other 7 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/struct/clone_spec.rb"
run_spec "$SPEC_DIR/core/struct/constants_spec.rb"
run_spec "$SPEC_DIR/core/struct/deconstruct_keys_spec.rb"
run_spec "$SPEC_DIR/core/struct/deconstruct_spec.rb"
run_spec "$SPEC_DIR/core/struct/dig_spec.rb"
run_spec "$SPEC_DIR/core/struct/dup_spec.rb"
run_spec "$SPEC_DIR/core/struct/each_pair_spec.rb"
run_spec "$SPEC_DIR/core/struct/each_spec.rb"
run_spec "$SPEC_DIR/core/struct/element_reference_spec.rb"
run_spec "$SPEC_DIR/core/struct/element_set_spec.rb"
run_spec "$SPEC_DIR/core/struct/eql_spec.rb"
run_spec "$SPEC_DIR/core/struct/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/struct/filter_spec.rb"
run_spec "$SPEC_DIR/core/struct/hash_spec.rb"
run_spec "$SPEC_DIR/core/struct/inspect_spec.rb"
run_spec "$SPEC_DIR/core/struct/instance_variable_get_spec.rb"
run_spec "$SPEC_DIR/core/struct/instance_variables_spec.rb"
run_spec "$SPEC_DIR/core/struct/keyword_init_spec.rb"
run_spec "$SPEC_DIR/core/struct/length_spec.rb"
run_spec "$SPEC_DIR/core/struct/members_spec.rb"
run_spec "$SPEC_DIR/core/struct/select_spec.rb"
run_spec "$SPEC_DIR/core/struct/size_spec.rb"
run_spec "$SPEC_DIR/core/struct/struct_spec.rb"
run_spec "$SPEC_DIR/core/struct/to_a_spec.rb"
run_spec "$SPEC_DIR/core/struct/to_h_spec.rb"
run_spec "$SPEC_DIR/core/struct/to_s_spec.rb"
run_spec "$SPEC_DIR/core/struct/values_at_spec.rb"
run_spec "$SPEC_DIR/core/struct/values_spec.rb"
# run_spec "$SPEC_DIR/core/struct"  # the other 2 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/data"

# 4.26 - 4.30: Strings and Patterns
run_spec "$SPEC_DIR/core/string/empty_spec.rb"
run_spec "$SPEC_DIR/core/string/hash_spec.rb"
run_spec "$SPEC_DIR/core/string/hex_spec.rb"
run_spec "$SPEC_DIR/core/string/oct_spec.rb"
run_spec "$SPEC_DIR/core/string/start_with_spec.rb"
run_spec "$SPEC_DIR/core/string/string_spec.rb"
run_spec "$SPEC_DIR/core/string/to_r_spec.rb"
run_spec "$SPEC_DIR/core/string/to_s_spec.rb"
run_spec "$SPEC_DIR/core/string/to_str_spec.rb"
# run_spec "$SPEC_DIR/core/string"  # the other 105 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/symbol/capitalize_spec.rb"
run_spec "$SPEC_DIR/core/symbol/case_compare_spec.rb"
run_spec "$SPEC_DIR/core/symbol/comparison_spec.rb"
run_spec "$SPEC_DIR/core/symbol/downcase_spec.rb"
run_spec "$SPEC_DIR/core/symbol/dup_spec.rb"
run_spec "$SPEC_DIR/core/symbol/empty_spec.rb"
run_spec "$SPEC_DIR/core/symbol/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/symbol/intern_spec.rb"
run_spec "$SPEC_DIR/core/symbol/length_spec.rb"
run_spec "$SPEC_DIR/core/symbol/match_spec.rb"
run_spec "$SPEC_DIR/core/symbol/name_spec.rb"
run_spec "$SPEC_DIR/core/symbol/next_spec.rb"
run_spec "$SPEC_DIR/core/symbol/size_spec.rb"
run_spec "$SPEC_DIR/core/symbol/start_with_spec.rb"
run_spec "$SPEC_DIR/core/symbol/succ_spec.rb"
run_spec "$SPEC_DIR/core/symbol/swapcase_spec.rb"
run_spec "$SPEC_DIR/core/symbol/symbol_spec.rb"
run_spec "$SPEC_DIR/core/symbol/to_sym_spec.rb"
run_spec "$SPEC_DIR/core/symbol/upcase_spec.rb"
# run_spec "$SPEC_DIR/core/symbol"  # the other 10 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/regexp/case_compare_spec.rb"
run_spec "$SPEC_DIR/core/regexp/casefold_spec.rb"
run_spec "$SPEC_DIR/core/regexp/eql_spec.rb"
run_spec "$SPEC_DIR/core/regexp/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/regexp/hash_spec.rb"
run_spec "$SPEC_DIR/core/regexp/last_match_spec.rb"
run_spec "$SPEC_DIR/core/regexp/named_captures_spec.rb"
run_spec "$SPEC_DIR/core/regexp/names_spec.rb"
# run_spec "$SPEC_DIR/core/regexp"  # the other 16 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/encoding/replicate_spec.rb"
# run_spec "$SPEC_DIR/core/encoding"  # the other 16 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/matchdata/allocate_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/begin_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/captures_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/deconstruct_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/dup_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/end_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/eql_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/equal_value_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/hash_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/inspect_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/length_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/match_length_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/match_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/named_captures_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/names_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/offset_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/regexp_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/size_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/to_a_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/to_s_spec.rb"
run_spec "$SPEC_DIR/core/matchdata/values_at_spec.rb"
# run_spec "$SPEC_DIR/core/matchdata"  # the other 8 files are enabled one at a time as they pass

# 4.31 - 4.34: Callables and Introspection
# run_spec "$SPEC_DIR/core/proc"
# run_spec "$SPEC_DIR/core/method"
run_spec "$SPEC_DIR/core/unboundmethod/name_spec.rb"
run_spec "$SPEC_DIR/core/unboundmethod/original_name_spec.rb"
run_spec "$SPEC_DIR/core/unboundmethod/private_spec.rb"
run_spec "$SPEC_DIR/core/unboundmethod/protected_spec.rb"
run_spec "$SPEC_DIR/core/unboundmethod/public_spec.rb"
run_spec "$SPEC_DIR/core/unboundmethod/arity_spec.rb"
run_spec "$SPEC_DIR/core/unboundmethod/eql_spec.rb"
run_spec "$SPEC_DIR/core/unboundmethod/inspect_spec.rb"
run_spec "$SPEC_DIR/core/unboundmethod/parameters_spec.rb"
run_spec "$SPEC_DIR/core/unboundmethod/super_method_spec.rb"
run_spec "$SPEC_DIR/core/unboundmethod/to_s_spec.rb"
# run_spec "$SPEC_DIR/core/unboundmethod"  # the other 8 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/binding/receiver_spec.rb"
# run_spec "$SPEC_DIR/core/binding"  # the other 8 files are enabled one at a time as they pass

# 4.35 - 4.39: IO and Filesystem
# run_spec "$SPEC_DIR/core/io"
run_spec "$SPEC_DIR/core/file/inspect_spec.rb"
# run_spec "$SPEC_DIR/core/file"  # the other 67 files are enabled one at a time as they pass
# run_spec "$SPEC_DIR/core/dir"
# run_spec "$SPEC_DIR/core/filetest"
run_spec "$SPEC_DIR/core/env/clear_spec.rb"
run_spec "$SPEC_DIR/core/env/delete_if_spec.rb"
run_spec "$SPEC_DIR/core/env/filter_spec.rb"
run_spec "$SPEC_DIR/core/env/inspect_spec.rb"
run_spec "$SPEC_DIR/core/env/invert_spec.rb"
run_spec "$SPEC_DIR/core/env/keep_if_spec.rb"
run_spec "$SPEC_DIR/core/env/length_spec.rb"
run_spec "$SPEC_DIR/core/env/reject_spec.rb"
run_spec "$SPEC_DIR/core/env/select_spec.rb"
run_spec "$SPEC_DIR/core/env/size_spec.rb"
# run_spec "$SPEC_DIR/core/env"  # the other 35 files are enabled one at a time as they pass

# 4.40 - 4.46: Concurrency
# run_spec "$SPEC_DIR/core/thread"
# run_spec "$SPEC_DIR/core/fiber"
# run_spec "$SPEC_DIR/core/mutex"
# run_spec "$SPEC_DIR/core/conditionvariable"
run_spec "$SPEC_DIR/core/queue/clear_spec.rb"
run_spec "$SPEC_DIR/core/queue/empty_spec.rb"
run_spec "$SPEC_DIR/core/queue/length_spec.rb"
run_spec "$SPEC_DIR/core/queue/size_spec.rb"
# run_spec "$SPEC_DIR/core/queue"  # the other 11 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/sizedqueue/clear_spec.rb"
run_spec "$SPEC_DIR/core/sizedqueue/empty_spec.rb"
run_spec "$SPEC_DIR/core/sizedqueue/length_spec.rb"
run_spec "$SPEC_DIR/core/sizedqueue/size_spec.rb"
# run_spec "$SPEC_DIR/core/sizedqueue"  # the other 12 files are enabled one at a time as they pass
# run_spec "$SPEC_DIR/core/threadgroup"

# 4.47 - 4.55: Other
run_spec "$SPEC_DIR/core/gc/start_spec.rb"
# run_spec "$SPEC_DIR/core/gc"  # the other 10 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/objectspace/garbage_collect_spec.rb"
# run_spec "$SPEC_DIR/core/objectspace"  # the other 6 files are enabled one at a time as they pass
# run_spec "$SPEC_DIR/core/random"
run_spec "$SPEC_DIR/core/time/asctime_spec.rb"
run_spec "$SPEC_DIR/core/time/ceil_spec.rb"
run_spec "$SPEC_DIR/core/time/ctime_spec.rb"
run_spec "$SPEC_DIR/core/time/day_spec.rb"
run_spec "$SPEC_DIR/core/time/deconstruct_keys_spec.rb"
run_spec "$SPEC_DIR/core/time/dst_spec.rb"
run_spec "$SPEC_DIR/core/time/eql_spec.rb"
run_spec "$SPEC_DIR/core/time/floor_spec.rb"
run_spec "$SPEC_DIR/core/time/friday_spec.rb"
run_spec "$SPEC_DIR/core/time/getgm_spec.rb"
run_spec "$SPEC_DIR/core/time/getutc_spec.rb"
run_spec "$SPEC_DIR/core/time/gmt_spec.rb"
run_spec "$SPEC_DIR/core/time/gmt_offset_spec.rb"
run_spec "$SPEC_DIR/core/time/dup_spec.rb"
run_spec "$SPEC_DIR/core/time/gmtime_spec.rb"
run_spec "$SPEC_DIR/core/time/gmtoff_spec.rb"
run_spec "$SPEC_DIR/core/time/hash_spec.rb"
run_spec "$SPEC_DIR/core/time/hour_spec.rb"
run_spec "$SPEC_DIR/core/time/isdst_spec.rb"
run_spec "$SPEC_DIR/core/time/iso8601_spec.rb"
run_spec "$SPEC_DIR/core/time/mday_spec.rb"
run_spec "$SPEC_DIR/core/time/min_spec.rb"
run_spec "$SPEC_DIR/core/time/minus_spec.rb"
run_spec "$SPEC_DIR/core/time/mon_spec.rb"
run_spec "$SPEC_DIR/core/time/monday_spec.rb"
run_spec "$SPEC_DIR/core/time/month_spec.rb"
run_spec "$SPEC_DIR/core/time/nsec_spec.rb"
run_spec "$SPEC_DIR/core/time/plus_spec.rb"
run_spec "$SPEC_DIR/core/time/round_spec.rb"
run_spec "$SPEC_DIR/core/time/saturday_spec.rb"
run_spec "$SPEC_DIR/core/time/sec_spec.rb"
run_spec "$SPEC_DIR/core/time/subsec_spec.rb"
run_spec "$SPEC_DIR/core/time/sunday_spec.rb"
run_spec "$SPEC_DIR/core/time/thursday_spec.rb"
run_spec "$SPEC_DIR/core/time/time_spec.rb"
run_spec "$SPEC_DIR/core/time/to_a_spec.rb"
run_spec "$SPEC_DIR/core/time/to_f_spec.rb"
run_spec "$SPEC_DIR/core/time/to_i_spec.rb"
run_spec "$SPEC_DIR/core/time/to_r_spec.rb"
run_spec "$SPEC_DIR/core/time/tuesday_spec.rb"
run_spec "$SPEC_DIR/core/time/tv_nsec_spec.rb"
run_spec "$SPEC_DIR/core/time/tv_sec_spec.rb"
run_spec "$SPEC_DIR/core/time/tv_usec_spec.rb"
run_spec "$SPEC_DIR/core/time/usec_spec.rb"
run_spec "$SPEC_DIR/core/time/utc_offset_spec.rb"
run_spec "$SPEC_DIR/core/time/wday_spec.rb"
run_spec "$SPEC_DIR/core/time/wednesday_spec.rb"
run_spec "$SPEC_DIR/core/time/xmlschema_spec.rb"
run_spec "$SPEC_DIR/core/time/yday_spec.rb"
run_spec "$SPEC_DIR/core/time/year_spec.rb"
# run_spec "$SPEC_DIR/core/time"  # the other 15 files are enabled one at a time as they pass
run_spec "$SPEC_DIR/core/process/abort_spec.rb"
run_spec "$SPEC_DIR/core/process/fork_spec.rb"
run_spec "$SPEC_DIR/core/process/pid_spec.rb"
# run_spec "$SPEC_DIR/core/process"  # the other 37 files are enabled one at a time as they pass
# run_spec "$SPEC_DIR/core/marshal"
# run_spec "$SPEC_DIR/core/tracepoint"
run_spec "$SPEC_DIR/core/refinement/refined_class_spec.rb"
# run_spec "$SPEC_DIR/core/refinement"  # the other 7 files are enabled one at a time as they pass
# run_spec "$SPEC_DIR/core/builtin_constants"

run_spec "$SPEC_DIR/language/comment_spec.rb"
run_spec "$SPEC_DIR/language/line_spec.rb"
run_spec "$SPEC_DIR/language/range_spec.rb"
run_spec "$SPEC_DIR/language/safe_spec.rb"
run_spec "$SPEC_DIR/language/throw_spec.rb"
run_spec "$SPEC_DIR/language/unless_spec.rb"
run_spec "$SPEC_DIR/language/not_spec.rb"
run_spec "$SPEC_DIR/language/private_spec.rb"
# run_spec "$SPEC_DIR/language"  # the other 59 files are enabled one at a time as they pass

run_spec "$SPEC_DIR/library/abbrev/abbrev_spec.rb"
run_spec "$SPEC_DIR/library/base64/urlsafe_decode64_spec.rb"
run_spec "$SPEC_DIR/library/base64/urlsafe_encode64_spec.rb"
run_spec "$SPEC_DIR/library/singleton/clone_spec.rb"
run_spec "$SPEC_DIR/library/singleton/dump_spec.rb"
run_spec "$SPEC_DIR/library/singleton/dup_spec.rb"
run_spec "$SPEC_DIR/library/singleton/new_spec.rb"
run_spec "$SPEC_DIR/library/observer/add_observer_spec.rb"
run_spec "$SPEC_DIR/library/observer/count_observers_spec.rb"
run_spec "$SPEC_DIR/library/observer/delete_observer_spec.rb"
run_spec "$SPEC_DIR/library/observer/delete_observers_spec.rb"
run_spec "$SPEC_DIR/library/observer/notify_observers_spec.rb"
run_spec "$SPEC_DIR/library/securerandom/hex_spec.rb"
run_spec "$SPEC_DIR/library/stringio/closed_read_spec.rb"
run_spec "$SPEC_DIR/library/stringio/closed_write_spec.rb"
run_spec "$SPEC_DIR/library/stringio/eof_spec.rb"
run_spec "$SPEC_DIR/library/stringio/fcntl_spec.rb"
run_spec "$SPEC_DIR/library/stringio/fileno_spec.rb"
run_spec "$SPEC_DIR/library/stringio/flush_spec.rb"
run_spec "$SPEC_DIR/library/stringio/fsync_spec.rb"
run_spec "$SPEC_DIR/library/stringio/isatty_spec.rb"
run_spec "$SPEC_DIR/library/stringio/length_spec.rb"
run_spec "$SPEC_DIR/library/stringio/path_spec.rb"
run_spec "$SPEC_DIR/library/stringio/pid_spec.rb"
run_spec "$SPEC_DIR/library/stringio/pos_spec.rb"
run_spec "$SPEC_DIR/library/stringio/size_spec.rb"
run_spec "$SPEC_DIR/library/stringio/sync_spec.rb"
run_spec "$SPEC_DIR/library/stringio/tell_spec.rb"
run_spec "$SPEC_DIR/library/stringio/tty_spec.rb"
run_spec "$SPEC_DIR/library/stringio/closed_spec.rb"
run_spec "$SPEC_DIR/library/stringio/append_spec.rb"
run_spec "$SPEC_DIR/library/stringio/close_spec.rb"
run_spec "$SPEC_DIR/library/stringio/close_read_spec.rb"
run_spec "$SPEC_DIR/library/stringio/close_write_spec.rb"
run_spec "$SPEC_DIR/library/stringio/each_byte_spec.rb"
run_spec "$SPEC_DIR/library/stringio/each_char_spec.rb"
run_spec "$SPEC_DIR/library/stringio/getbyte_spec.rb"
run_spec "$SPEC_DIR/library/stringio/getpass_spec.rb"
run_spec "$SPEC_DIR/library/stringio/getc_spec.rb"
run_spec "$SPEC_DIR/library/stringio/inspect_spec.rb"
run_spec "$SPEC_DIR/library/stringio/internal_encoding_spec.rb"
run_spec "$SPEC_DIR/library/stringio/lineno_spec.rb"
run_spec "$SPEC_DIR/library/stringio/new_spec.rb"
run_spec "$SPEC_DIR/library/stringio/print_spec.rb"
run_spec "$SPEC_DIR/library/stringio/putc_spec.rb"
run_spec "$SPEC_DIR/library/stringio/readbyte_spec.rb"
run_spec "$SPEC_DIR/library/stringio/readchar_spec.rb"
run_spec "$SPEC_DIR/library/stringio/rewind_spec.rb"
run_spec "$SPEC_DIR/library/stringio/string_spec.rb"
run_spec "$SPEC_DIR/library/stringio/stringio_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/append_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/beginning_of_line_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/bol_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/captures_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/charpos_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/check_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/check_until_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/concat_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/dup_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/element_reference_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/eos_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/exist_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/fixed_anchor_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/initialize_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/inspect_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/match_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/matched_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/matched_size_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/must_C_version_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/named_captures_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/peek_byte_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/post_match_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/pre_match_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/reset_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/rest_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/rest_size_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/scan_byte_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/scan_full_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/scan_integer_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/scan_until_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/search_full_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/size_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/skip_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/skip_until_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/string_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/terminate_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/unscan_spec.rb"
run_spec "$SPEC_DIR/library/stringscanner/values_at_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/delete_field_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/element_reference_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/element_set_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/equal_value_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/frozen_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/initialize_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/inspect_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/marshal_dump_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/marshal_load_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/method_missing_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/new_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/to_h_spec.rb"
run_spec "$SPEC_DIR/library/openstruct/to_s_spec.rb"
run_spec "$SPEC_DIR/library/prime/instance_spec.rb"
run_spec "$SPEC_DIR/library/prime/int_from_prime_division_spec.rb"
run_spec "$SPEC_DIR/library/prime/integer/from_prime_division_spec.rb"
run_spec "$SPEC_DIR/library/prime/integer/prime_spec.rb"
run_spec "$SPEC_DIR/library/prime/integer/prime_division_spec.rb"
run_spec "$SPEC_DIR/library/prime/next_spec.rb"
run_spec "$SPEC_DIR/library/prime/prime_spec.rb"
run_spec "$SPEC_DIR/library/prime/prime_division_spec.rb"
run_spec "$SPEC_DIR/library/prime/succ_spec.rb"
run_spec "$SPEC_DIR/library/matrix/I_spec.rb"
run_spec "$SPEC_DIR/library/matrix/antisymmetric_spec.rb"
run_spec "$SPEC_DIR/library/matrix/clone_spec.rb"
run_spec "$SPEC_DIR/library/matrix/collect_spec.rb"
run_spec "$SPEC_DIR/library/matrix/column_size_spec.rb"
run_spec "$SPEC_DIR/library/matrix/column_spec.rb"
run_spec "$SPEC_DIR/library/matrix/conj_spec.rb"
run_spec "$SPEC_DIR/library/matrix/conjugate_spec.rb"
run_spec "$SPEC_DIR/library/matrix/constructor_spec.rb"
run_spec "$SPEC_DIR/library/matrix/diagonal_spec.rb"
run_spec "$SPEC_DIR/library/matrix/each_spec.rb"
run_spec "$SPEC_DIR/library/matrix/each_with_index_spec.rb"
run_spec "$SPEC_DIR/library/matrix/element_reference_spec.rb"
run_spec "$SPEC_DIR/library/matrix/empty_spec.rb"
run_spec "$SPEC_DIR/library/matrix/hash_spec.rb"
run_spec "$SPEC_DIR/library/matrix/hermitian_spec.rb"
run_spec "$SPEC_DIR/library/matrix/identity_spec.rb"
run_spec "$SPEC_DIR/library/matrix/imag_spec.rb"
run_spec "$SPEC_DIR/library/matrix/imaginary_spec.rb"
run_spec "$SPEC_DIR/library/matrix/inverse_from_spec.rb"
run_spec "$SPEC_DIR/library/matrix/lower_triangular_spec.rb"
run_spec "$SPEC_DIR/library/matrix/map_spec.rb"
run_spec "$SPEC_DIR/library/matrix/minus_spec.rb"
run_spec "$SPEC_DIR/library/matrix/normal_spec.rb"
run_spec "$SPEC_DIR/library/matrix/orthogonal_spec.rb"
run_spec "$SPEC_DIR/library/matrix/plus_spec.rb"
run_spec "$SPEC_DIR/library/matrix/rank_spec.rb"
run_spec "$SPEC_DIR/library/matrix/real_spec.rb"
run_spec "$SPEC_DIR/library/matrix/round_spec.rb"
run_spec "$SPEC_DIR/library/matrix/row_size_spec.rb"
run_spec "$SPEC_DIR/library/matrix/row_spec.rb"
run_spec "$SPEC_DIR/library/matrix/row_vector_spec.rb"
run_spec "$SPEC_DIR/library/matrix/rows_spec.rb"
run_spec "$SPEC_DIR/library/matrix/scalar/Fail_spec.rb"
run_spec "$SPEC_DIR/library/matrix/scalar/Raise_spec.rb"
run_spec "$SPEC_DIR/library/matrix/scalar/divide_spec.rb"
run_spec "$SPEC_DIR/library/matrix/scalar/exponent_spec.rb"
run_spec "$SPEC_DIR/library/matrix/scalar/included_spec.rb"
run_spec "$SPEC_DIR/library/matrix/scalar/initialize_spec.rb"
run_spec "$SPEC_DIR/library/matrix/scalar/minus_spec.rb"
run_spec "$SPEC_DIR/library/matrix/scalar/multiply_spec.rb"
run_spec "$SPEC_DIR/library/matrix/scalar/plus_spec.rb"
run_spec "$SPEC_DIR/library/matrix/scalar_spec.rb"
run_spec "$SPEC_DIR/library/matrix/symmetric_spec.rb"
run_spec "$SPEC_DIR/library/matrix/to_a_spec.rb"
run_spec "$SPEC_DIR/library/matrix/to_s_spec.rb"
run_spec "$SPEC_DIR/library/matrix/tr_spec.rb"
run_spec "$SPEC_DIR/library/matrix/trace_spec.rb"
run_spec "$SPEC_DIR/library/matrix/unit_spec.rb"
run_spec "$SPEC_DIR/library/matrix/upper_triangular_spec.rb"
run_spec "$SPEC_DIR/library/matrix/vector/cross_product_spec.rb"
run_spec "$SPEC_DIR/library/matrix/vector/eql_spec.rb"
run_spec "$SPEC_DIR/library/matrix/vector/normalize_spec.rb"
run_spec "$SPEC_DIR/library/matrix/zero_spec.rb"
run_spec "$SPEC_DIR/library/matrix/coerce_spec.rb"
run_spec "$SPEC_DIR/library/matrix/det_spec.rb"
run_spec "$SPEC_DIR/library/matrix/determinant_spec.rb"
run_spec "$SPEC_DIR/library/matrix/divide_spec.rb"
run_spec "$SPEC_DIR/library/matrix/equal_value_spec.rb"
run_spec "$SPEC_DIR/library/matrix/regular_spec.rb"
run_spec "$SPEC_DIR/library/matrix/singular_spec.rb"
run_spec "$SPEC_DIR/library/matrix/unitary_spec.rb"
run_spec "$SPEC_DIR/library/date/accessor_spec.rb"
run_spec "$SPEC_DIR/library/date/add_month_spec.rb"
run_spec "$SPEC_DIR/library/date/add_spec.rb"
run_spec "$SPEC_DIR/library/date/ajd_spec.rb"
run_spec "$SPEC_DIR/library/date/ajd_to_amjd_spec.rb"
run_spec "$SPEC_DIR/library/date/ajd_to_jd_spec.rb"
run_spec "$SPEC_DIR/library/date/amjd_spec.rb"
run_spec "$SPEC_DIR/library/date/amjd_to_ajd_spec.rb"
run_spec "$SPEC_DIR/library/date/append_spec.rb"
run_spec "$SPEC_DIR/library/date/asctime_spec.rb"
run_spec "$SPEC_DIR/library/date/boat_spec.rb"
run_spec "$SPEC_DIR/library/date/case_compare_spec.rb"
run_spec "$SPEC_DIR/library/date/civil_spec.rb"
run_spec "$SPEC_DIR/library/date/commercial_spec.rb"
# run_spec "$SPEC_DIR/library/date/constants_spec.rb"  # 7 of its 8 examples pass; the last needs a frozen String to answer FrozenError from `<<`
run_spec "$SPEC_DIR/library/date/commercial_to_jd_spec.rb"
run_spec "$SPEC_DIR/library/date/comparison_spec.rb"
run_spec "$SPEC_DIR/library/date/conversions_spec.rb"
run_spec "$SPEC_DIR/library/date/ctime_spec.rb"
run_spec "$SPEC_DIR/library/date/cwday_spec.rb"
run_spec "$SPEC_DIR/library/date/cweek_spec.rb"
run_spec "$SPEC_DIR/library/date/cwyear_spec.rb"
run_spec "$SPEC_DIR/library/date/day_fraction_spec.rb"
run_spec "$SPEC_DIR/library/date/day_fraction_to_time_spec.rb"
run_spec "$SPEC_DIR/library/date/day_spec.rb"
run_spec "$SPEC_DIR/library/date/deconstruct_keys_spec.rb"
run_spec "$SPEC_DIR/library/date/downto_spec.rb"
run_spec "$SPEC_DIR/library/date/england_spec.rb"
run_spec "$SPEC_DIR/library/date/eql_spec.rb"
run_spec "$SPEC_DIR/library/date/friday_spec.rb"
run_spec "$SPEC_DIR/library/date/gregorian_leap_spec.rb"
run_spec "$SPEC_DIR/library/date/gregorian_spec.rb"
run_spec "$SPEC_DIR/library/date/hash_spec.rb"
run_spec "$SPEC_DIR/library/date/infinity_spec.rb"
run_spec "$SPEC_DIR/library/date/inspect_spec.rb"
run_spec "$SPEC_DIR/library/date/iso8601_spec.rb"
run_spec "$SPEC_DIR/library/date/italy_spec.rb"
run_spec "$SPEC_DIR/library/date/jd_spec.rb"
run_spec "$SPEC_DIR/library/date/jd_to_ajd_spec.rb"
run_spec "$SPEC_DIR/library/date/jd_to_civil_spec.rb"
run_spec "$SPEC_DIR/library/date/jd_to_commercial_spec.rb"
run_spec "$SPEC_DIR/library/date/jd_to_ld_spec.rb"
run_spec "$SPEC_DIR/library/date/jd_to_mjd_spec.rb"
run_spec "$SPEC_DIR/library/date/jd_to_ordinal_spec.rb"
run_spec "$SPEC_DIR/library/date/jd_to_wday_spec.rb"
run_spec "$SPEC_DIR/library/date/julian_leap_spec.rb"
run_spec "$SPEC_DIR/library/date/julian_spec.rb"
run_spec "$SPEC_DIR/library/date/ld_spec.rb"
run_spec "$SPEC_DIR/library/date/ld_to_jd_spec.rb"
run_spec "$SPEC_DIR/library/date/leap_spec.rb"
run_spec "$SPEC_DIR/library/date/mday_spec.rb"
run_spec "$SPEC_DIR/library/date/minus_month_spec.rb"
run_spec "$SPEC_DIR/library/date/minus_spec.rb"
run_spec "$SPEC_DIR/library/date/mjd_spec.rb"
run_spec "$SPEC_DIR/library/date/mjd_to_jd_spec.rb"
run_spec "$SPEC_DIR/library/date/mon_spec.rb"
run_spec "$SPEC_DIR/library/date/monday_spec.rb"
run_spec "$SPEC_DIR/library/date/month_spec.rb"
run_spec "$SPEC_DIR/library/date/new_spec.rb"
run_spec "$SPEC_DIR/library/date/new_start_spec.rb"
run_spec "$SPEC_DIR/library/date/next_day_spec.rb"
run_spec "$SPEC_DIR/library/date/next_month_spec.rb"
run_spec "$SPEC_DIR/library/date/next_spec.rb"
run_spec "$SPEC_DIR/library/date/next_year_spec.rb"
run_spec "$SPEC_DIR/library/date/ordinal_spec.rb"
run_spec "$SPEC_DIR/library/date/ordinal_to_jd_spec.rb"
run_spec "$SPEC_DIR/library/date/parse_spec.rb"
run_spec "$SPEC_DIR/library/date/plus_spec.rb"
run_spec "$SPEC_DIR/library/date/prev_day_spec.rb"
run_spec "$SPEC_DIR/library/date/prev_month_spec.rb"
run_spec "$SPEC_DIR/library/date/prev_year_spec.rb"
run_spec "$SPEC_DIR/library/date/relationship_spec.rb"
run_spec "$SPEC_DIR/library/date/rfc3339_spec.rb"
run_spec "$SPEC_DIR/library/date/right_shift_spec.rb"
run_spec "$SPEC_DIR/library/date/saturday_spec.rb"
run_spec "$SPEC_DIR/library/date/start_spec.rb"
run_spec "$SPEC_DIR/library/date/step_spec.rb"
# run_spec "$SPEC_DIR/library/date/strftime_spec.rb"  # 45 of its 46 examples pass; the last needs DateTime
run_spec "$SPEC_DIR/library/date/strptime_spec.rb"
run_spec "$SPEC_DIR/library/date/succ_spec.rb"
run_spec "$SPEC_DIR/library/date/sunday_spec.rb"
run_spec "$SPEC_DIR/library/date/thursday_spec.rb"
run_spec "$SPEC_DIR/library/date/time_to_day_fraction_spec.rb"
run_spec "$SPEC_DIR/library/date/to_s_spec.rb"
run_spec "$SPEC_DIR/library/date/today_spec.rb"
run_spec "$SPEC_DIR/library/date/tuesday_spec.rb"
run_spec "$SPEC_DIR/library/date/upto_spec.rb"
run_spec "$SPEC_DIR/library/date/valid_civil_spec.rb"
run_spec "$SPEC_DIR/library/date/valid_commercial_spec.rb"
run_spec "$SPEC_DIR/library/date/valid_date_spec.rb"
run_spec "$SPEC_DIR/library/date/valid_jd_spec.rb"
run_spec "$SPEC_DIR/library/date/valid_ordinal_spec.rb"
run_spec "$SPEC_DIR/library/date/valid_time_spec.rb"
run_spec "$SPEC_DIR/library/date/wday_spec.rb"
run_spec "$SPEC_DIR/library/date/wednesday_spec.rb"
run_spec "$SPEC_DIR/library/date/yday_spec.rb"
run_spec "$SPEC_DIR/library/date/year_spec.rb"
run_spec "$SPEC_DIR/library/date/zone_to_diff_spec.rb"
# run_spec "$SPEC_DIR/library"  # the rest are enabled one at a time as they pass

run_spec "$SPEC_DIR/command_line/dash_r_spec.rb"
# run_spec "$SPEC_DIR/command_line"  # the other 31 files are enabled one at a time as they pass

run_spec "$SPEC_DIR/security/cve_2018_16396_spec.rb"
run_spec "$SPEC_DIR/security/cve_2020_10663_spec.rb"
# run_spec "$SPEC_DIR/security"  # the other 12 files are enabled one at a time as they pass

# ──────────────────────────────────────────────────────────────────────────
# Parallel execution. mspec invocations are independent processes, so we
# fan them out via xargs and rejoin them in queue order for output.
# ──────────────────────────────────────────────────────────────────────────

if [ "$SPEC_COUNT" -eq 0 ]; then
  exit 0
fi

# Worker script. xargs invokes it as `worker <idx> <spec>`. mspec output is
# tee'd to "$WORK_DIR/<idx>.out" (consulted later for the summary line) AND
# streamed through `grep --line-buffered` to stdout, stripping the per-spec
# framing noise — empty lines, the `$ /path/...` command echo, the
# `metorex (ruby-compatible)` banner, the `Finished in …` timing, and the
# `N files, …` summary. What's left is the dot/E/F progress lines and any
# failure detail — in real time as each spec finishes. (Mspec emits all dots
# on a single line, so they appear together when that spec completes; one
# spec's dot line per spec arrival, not per individual test.)
export MSPEC METOREX WORK_DIR SPEC_TEMP_ROOT
WORKER="$WORK_DIR/worker.sh"
cat > "$WORKER" <<'WORKER_EOF'
#!/usr/bin/env bash
idx=$1
spec=$2
# Each worker gets its own scratch directory, so two specs running at once
# cannot land on the same file name.
export SPEC_TEMP_DIR="$SPEC_TEMP_ROOT/$idx"
mkdir -p "$SPEC_TEMP_DIR"
"$MSPEC" -t "$METOREX" "$spec" 2>&1 \
  | tee "$WORK_DIR/$idx.out" \
  | grep --line-buffered -v -E '^$|^\$ |^metorex \(ruby-compatible\)$|^Finished in [0-9.]+ seconds$|^[0-9]+ files?, [0-9]+ examples?, [0-9]+ expectations?, [0-9]+ failures?, [0-9]+ errors?, [0-9]+ tagged$' \
  || true
echo "${PIPESTATUS[0]}" > "$WORK_DIR/$idx.code"
WORKER_EOF
chmod +x "$WORKER"

# Feed null-delimited (idx, path) pairs to xargs so workers don't have to
# split arguments themselves and paths with spaces stay intact.
{
  i=0
  while [ "$i" -lt "$SPEC_COUNT" ]; do
    printf '%s\0%s\0' "$i" "${SPEC_PATHS[$i]}"
    i=$((i + 1))
  done
} | xargs -0 -n 2 -P "$JOBS" "$WORKER"

# Workers already streamed their output. Walk the .out files silently to
# fold summary lines into the running totals and detect failures.
i=0
while [ "$i" -lt "$SPEC_COUNT" ]; do
  out_file="$WORK_DIR/$i.out"
  code_file="$WORK_DIR/$i.code"
  if [ -f "$code_file" ]; then
    code=$(cat "$code_file")
    if [ "$code" != "0" ]; then
      ANY_FAILED=1
    fi
  fi
  if [ -f "$out_file" ]; then
    summary=$(grep -E '^[0-9]+ files?, [0-9]+ examples?, [0-9]+ expectations?, [0-9]+ failures?, [0-9]+ errors?, [0-9]+ tagged$' "$out_file" | tail -1)
    if [ -n "$summary" ]; then
      read -r f _ e _ ex _ fl _ er _ tg _ <<< "$summary"
      TOTAL_FILES=$((TOTAL_FILES + f))
      TOTAL_EXAMPLES=$((TOTAL_EXAMPLES + e))
      TOTAL_EXPECTATIONS=$((TOTAL_EXPECTATIONS + ex))
      TOTAL_FAILURES=$((TOTAL_FAILURES + fl))
      TOTAL_ERRORS=$((TOTAL_ERRORS + er))
      TOTAL_TAGGED=$((TOTAL_TAGGED + tg))
    fi
  fi
  i=$((i + 1))
done

if [ "$ANY_FAILED" != "0" ]; then
  exit 1
fi
